this._s=this._s||{};(function(_){var window=this;
try{
_.kSq=function(a){if(a===2)return null;let b;try{b=window.localStorage}catch(c){return null}if(!b)return null;a=new jSq(b);if(!a.set("placeholder",0))return null;a.remove("placeholder");return a};var jSq=class{constructor(a){this.oa=a}get(a){if(!_.ca.navigator.cookieEnabled)return null;a=this.oa.getItem("udla::"+a);if(!a)return null;try{return JSON.parse(a)}catch(b){return null}}remove(a){_.ca.navigator.cookieEnabled&&this.oa.removeItem("udla::"+a)}set(a,b){if(!_.ca.navigator.cookieEnabled)return!1;try{return this.oa.setItem("udla::"+a,JSON.stringify(b)),!0}catch(c){return!1}}};
}catch(e){_._DumpException(e)}
try{
_.URq=class extends _.m{constructor(a){super(a)}Ct(){return _.lj(this,1)}Ca(){return _.Ei(this,1)}Ea(){return _.qj(this,2)}Aa(){return _.mi(this,2)}Ka(){return _.qj(this,3)}Ba(){return _.mi(this,3)}Da(){return _.qj(this,4)}getHeading(){return _.qj(this,7)}Aia(){return _.Wj(this,7)}setSpeed(a){return _.Xg(this,8,a)}};
}catch(e){_._DumpException(e)}
try{
_.RRq=class extends _.m{constructor(a){super(a)}Ba(){return _.Oi(this,4)}Da(){return _.bk(this,4)}Aa(){return _.$g(this,4)}Ca(){return _.n(this,_.AMb,5)}};
}catch(e){_._DumpException(e)}
try{
var Xcq,$cq,fdq,ddq;Xcq=function(a,b,c){this.yNc=a;this.Aa=b.name||null;this.Ba=b.fullName||null;this.oa={};for(a=0;a<c.length;a++)b=c[a],this.oa[b.oa]=b};_.Ycq=function(){};Xcq.prototype.getName=function(){return this.Aa};Xcq.prototype.getFullName=function(){return this.Ba};_.Zcq=function(a){a=_.zc(a.oa);a.sort(function(b,c){return b.oa-c.oa});return a};
$cq=function(a,b,c){this.parent_=a;this.oa=b;this.Ja=c.name;this.Ka=!!c.repeated;this.Ma=!!c.required;this.Aa=c.Oi;this.Ba=c.type;this.Da=!1;switch(this.Aa){case 3:case 4:case 6:case 16:case 18:case 2:case 1:this.Da=!0}this.Ea=c.lba||null;this.Ca=c.defaultValue};$cq.prototype.getName=function(){return this.Ja};$cq.prototype.Tqa=function(){if(this.Ca===void 0){const a=this.Ba;if(a===Boolean)this.Ca=!1;else if(a===Number)this.Ca=0;else if(a===String)this.Ca=this.Da?"0":"";else return new a}return this.Ca};
var adq=function(a){return a.Aa==11||a.Aa==10};$cq.prototype.isRepeated=function(){return this.Ka};$cq.prototype.isRequired=function(){return this.Ma};_.RZ=function(){this.Aa={};this.Ba=this.getDescriptor().oa;this.oa=this.Ca=null};_.bdq=function(a,b,c){c=c||a;for(const d in a.Aa){const e=Number(d);a.Ba[e]||b.call(c,e,a.Aa[d])}};_.aa=_.RZ.prototype;_.aa.has=function(a){return _.SZ(this,a.oa)};_.aa.arrayOf=function(a){return _.cdq(this,a.oa)};_.aa.get=function(a,b){return _.TZ(this,a.oa,b)};
_.aa.set=function(a,b){_.UZ(this,a.oa,b)};_.aa.add=function(a,b){ddq(this,a.oa,b)};_.aa.clear=function(a){_.edq(this,a.oa)};
_.aa.equals=function(a){if(!a||this.constructor!=a.constructor)return!1;const b=_.Zcq(this.getDescriptor());for(let f=0;f<b.length;f++){var c=b[f],d=c.oa;if(_.SZ(this,d)!=_.SZ(a,d))return!1;if(_.SZ(this,d)){const g=adq(c),h=fdq(this,d);d=fdq(a,d);if(c.isRepeated()){if(h.length!=d.length)return!1;for(let k=0;k<h.length;k++){c=h[k];var e=d[k];if(g?!c.equals(e):c!=e)return!1}}else if(g?!h.equals(d):h!=d)return!1}}return!0};
var gdq=function(a,b){const c=_.Zcq(a.getDescriptor());for(let f=0;f<c.length;f++){var d=c[f];const g=d.oa;if(_.SZ(b,g)){a.oa&&delete a.oa[d.oa];var e=adq(d);if(d.isRepeated()){d=_.cdq(b,g);for(let h=0;h<d.length;h++)ddq(a,g,e?d[h].clone():d[h])}else d=fdq(b,g),e?(e=fdq(a,g))?gdq(e,d):_.UZ(a,g,d.clone()):_.UZ(a,g,d)}}};_.RZ.prototype.clone=function(){const a=new this.constructor;a!=this&&(a.Aa={},a.oa&&(a.oa={}),gdq(a,this));return a};_.SZ=function(a,b){return a.Aa[b]!=null};
fdq=function(a,b){var c=a.Aa[b];return c==null?null:a.Ca?b in a.oa?a.oa[b]:(c=a.Ca.D7d(a.Ba[b],c),a.oa[b]=c):c};_.TZ=function(a,b,c){const d=fdq(a,b);return a.Ba[b].isRepeated()?d[c||0]:d};_.cdq=function(a,b){return fdq(a,b)||[]};_.hdq=function(a,b){return a.Ba[b].isRepeated()?_.SZ(a,b)?a.Aa[b].length:0:_.SZ(a,b)?1:0};_.UZ=function(a,b,c){a.Aa[b]=c;a.oa&&(a.oa[b]=c)};ddq=function(a,b,c){a.Aa[b]||(a.Aa[b]=[]);a.Aa[b].push(c);a.oa&&delete a.oa[b]};_.edq=function(a,b){delete a.Aa[b];a.oa&&delete a.oa[b]};
_.idq=function(a,b){const c=[],d=b[0];for(const e in b)e!=0&&c.push(new $cq(a,e,b[e]));return new Xcq(a,d,c)};_.Ycq.prototype.u9b=function(a,b){return adq(a)?this.serialize(b):typeof b!=="number"||isFinite(b)?b:b.toString()};_.Ycq.prototype.VEb=function(a,b){a=new a.yNc;this.oa(a,b);return a};
_.Ycq.prototype.d8b=function(a,b){if(adq(a))return b instanceof _.RZ?b:this.VEb(a.Ba.prototype.getDescriptor(),b);if(a.Aa==14)return typeof b==="string"&&jdq.test(b)&&(a=Number(b),a>0)?a:b;if(!a.Da)return b;a=a.Ba;if(a===String){if(typeof b==="number")return String(b)}else if(a===Number&&typeof b==="string"&&(b==="Infinity"||b==="-Infinity"||b==="NaN"||jdq.test(b)))return Number(b);return b};var jdq=/^-?[0-9]+$/;
}catch(e){_._DumpException(e)}
try{
_.Ivd=function(a,b){return _.uj(a,2,b)};
}catch(e){_._DumpException(e)}
try{
var lSq,mSq,rSq,tSq,uSq,vSq,wSq,ySq,zSq,ASq,DSq,ESq,FSq,GSq,HSq,ISq,JSq,KSq,LSq,MSq,NSq,PSq,QSq;lSq=function(a){return a===2?"EUULE":"UULE"};_.nSq=function(){_.Ae.get(lSq(2))!=null&&_.Ae.remove("EUULE","/");(mSq("j")||mSq("a"))&&_.Ae.remove("UULE","/")};mSq=function(a){var b=_.Ae.get(lSq(1));if(!b)return null;b=b.split("+");return b.length!=2||b[0]!=a?null:b[1]};rSq=function(a){switch(a){case 1:return oSq;case 2:return pSq;case 3:return qSq;default:throw Error("hw`"+a);}};
_.sSq=function(a){switch(_.n_(a)){case 0:return 0;case 1:return 1;case 2:return 2;case 3:return 3;case 5:return 4;case 6:return 5;default:return 0}};tSq=function(a){switch(a){case 1:return 2;case 2:return 3;case 3:return 4;case 1E3:return 5;case 1002:return 6;default:return 0}};uSq=function(a){return a===1||a===5};vSq=function(a){switch(a){case 1:return 2;case 2:return 3;case 3:return 1;case 4:return 5;default:return 0}};wSq=function(a){var b=vSq(a.Aa());b=_.o_(b);a=a.Ca();return _.Eb(b,_.AMb,2,a)};
ySq=function(a){return a instanceof _.xSq&&a.code===1};zSq=function(a){return a?a.Da()&&a.Ba()!==0?Promise.resolve(a):Promise.reject(new _.xSq(2,`Silk geolocation permissions API returned invalid permission value ${a.Aa()}.`)):Promise.reject(new _.xSq(2,"Silk geolocation permissions API returned null or undefined."))};
ASq=function(a){if(a instanceof _.ge){a:switch(a.jXb){case "feature_not_enabled":var b=1;break a;default:b=3}a=Promise.reject(new _.xSq(b,a.message))}else a=Promise.reject(new _.xSq(4,`Silk API returned an unknown error: ${a}`));return a};_.CSq=function(a,b,c){if(c&&a!==2)return new BSq(c,b)};DSq=function(a){return((a.mD*24+a.hours)*60+a.minutes)*60+a.uS};ESq=function(a,b){return _.xtb(a.oa,function(c){return c.getName()==b})||null};
FSq={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\v":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"};GSq={"'":"\\'"};
HSq=function(a){a=String(a);const b=['"'];for(let g=0;g<a.length;g++){var c=a.charAt(g),d=c.charCodeAt(0),e=g+1,f;if(!(f=FSq[c])){if(!(d>31&&d<127))if(c in GSq)c=GSq[c];else if(c in FSq)c=GSq[c]=FSq[c];else{d=c.charCodeAt(0);if(d>31&&d<127)f=c;else{if(d<256){if(f="\\x",d<16||d>256)f+="0"}else f="\\u",d<4096&&(f+="0");f+=d.toString(16).toUpperCase()}c=GSq[c]=f}f=c}b[e]=f}b.push('"');return b.join("")};ISq=class extends _.m{constructor(a){super(a)}};JSq=class extends _.m{constructor(a){super(a)}};
KSq=class extends _.m{constructor(a){super(a)}};LSq=class extends _.m{constructor(a){super(a)}getFieldOfView(){return _.n(this,KSq,8)}};MSq=class extends _.m{constructor(a){super(a)}Ct(){return _.Sd(this,3)}clearRect(){return _.Td(this,14)}Sc(){return _.n(this,ISq,10)}Qc(){return _.Mi(this,16)}xn(){return _.nj(this,16)}hasAttributes(){return _.fi(this,LSq,19)}};NSq=function(a){const b=new _.gC;b.setTime(a);return b};_.OSq=!!(_.Oh[43]&2);PSq=!!(_.Oh[43]&4);QSq=!!(_.Oh[43]&8);_.RSq=!!(_.Oh[89]&16);
_.SSq=!!(_.Oh[95]>>18&1);_.TSq=function(a){return a instanceof _.p_?a:new _.p_(2,`The geolocation API returned an unknown error: ${a}`)};_.p_=class extends Error{constructor(a,b){super(b);this.code=a}oa(){return this.code===1||this.code===1001}};var USq={jJf:0,B5e:1,y6e:2,npa:3,FJf:4,ygf:5,xgf:6,VIEWPORT:7,Pdf:8,Eif:9,Uaf:10,A5e:11,vcf:12,vef:13,zuf:14,MMf:-1},VSq={gJf:0,jnf:1,vvf:2,ojf:3,qjf:42,rjf:83,Yef:4,Exf:5,KDf:6,owf:41,iwf:44,o7e:12,Llf:11,R1e:17,m3e:54,v6e:68,DCf:7,Smf:8,Nzf:13,zpf:14,Uff:34,Fpf:15,vtf:16,uMf:18,tMf:20,bof:21,Nvf:22,EWe:23,mTd:24,mwf:25,nwf:59,xef:26,Hhf:27,D1e:28,gDf:29,Glf:30,Mlf:31,Flf:35,Rff:64,h3e:33,qCf:36,rtf:37,HWe:38,KWe:39,z6e:32,sLf:40,Tdf:43,jEf:45,mIf:46,lDf:47,kDf:48,fhf:49,ghf:50,fGf:52,Znf:55,pjf:53,
H7e:56,xzf:57,nDf:58,lff:60,l0e:61,Mef:62,Qff:63,j4e:65,Kef:66,s4c:67,fBf:69,n7e:70,UHf:71,ehf:72,LMf:-1,Nlf:9,Hlf:10,Jlf:19,YVe:73,csf:74,dsf:76,I7e:75,GWe:77,Lzf:78,WYe:79,bsf:80,IWe:81,pEf:82},WSq={oJf:0,HWd:1,ypf:2,Ilf:3,cof:4,Klf:5,Sff:6,Tff:12,XMf:7,YMf:8,Elf:9,jZe:10,XYe:11,kdf:13,zaf:101,xaf:102,yaf:103,Ttf:200},XSq={lAf:0,jAf:1,iAf:2,kAf:3,eAf:4,mAf:5,gAf:6,fAf:7,dAf:8,hAf:9},YSq={Otf:0,Mtf:1,Ntf:2},ZSq=function(){_.RZ.call(this)};_.Th(ZSq,_.RZ);var $Sq=null,aTq=function(){_.RZ.call(this)};
_.Th(aTq,_.RZ);var bTq=null,cTq=function(){_.RZ.call(this)};_.Th(cTq,_.RZ);var dTq=null,eTq=function(){_.RZ.call(this)};_.Th(eTq,_.RZ);var fTq=null,gTq=function(){_.RZ.call(this)};_.Th(gTq,_.RZ);var hTq=null;gTq.prototype.getType=function(){return _.TZ(this,1)};gTq.prototype.setType=function(a){_.UZ(this,1,a)};gTq.prototype.Oe=function(){return _.SZ(this,1)};
var iTq={Qif:0,Xrf:1,Zrf:2,mEf:3,UNKNOWN:4,hHf:5,Maf:6,WALKING:7,RUNNING:8,Orf:9,ZHf:10,Ycf:11,asf:12,Yrf:13,Lif:14,SLEEPING:15,Oif:16,Nif:17,Pif:18,Mif:19,Kif:20,Jif:21,Taf:-1E3},jTq=function(){_.RZ.call(this)};_.Th(jTq,_.RZ);var kTq=null,lTq=function(){_.RZ.call(this)};_.Th(lTq,_.RZ);var mTq=null;lTq.prototype.getFieldOfView=function(){return _.TZ(this,8)};
var nTq={Yuf:0,Ruf:1,Uuf:2,Xuf:3,Suf:4,Quf:5,Wuf:6,Vuf:7,Puf:8,Tuf:9},oTq={wif:0,uif:1,tif:2,vif:3,xif:4},pTq={Unf:0,Wnf:1,Qnf:2,Rnf:3,Snf:4,Vnf:5,Tnf:6},qTq={U1e:0,T1e:1,S1e:2},rTq={xLf:0,tLf:1,wLf:2,uLf:3,vLf:4},sTq=function(){_.RZ.call(this)};_.Th(sTq,_.RZ);var tTq=null;sTq.prototype.Sc=function(){return _.TZ(this,1)};sTq.prototype.Ln=function(){return _.TZ(this,3)};sTq.prototype.sD=function(){return _.SZ(this,3)};sTq.prototype.Kg=function(){return _.TZ(this,5)};
var uTq={ZIf:0,g4c:1,Rof:2,ugf:3},vTq={UNKNOWN:0,bgf:1,dhf:2,XXe:3},wTq=function(){_.RZ.call(this)};_.Th(wTq,_.RZ);var xTq=null,yTq={Zqf:0,Dvf:1E3},zTq=function(){_.RZ.call(this)};_.Th(zTq,_.RZ);var ATq=null,BTq=function(){_.RZ.call(this)};_.Th(BTq,_.RZ);var CTq=null;_.aa=BTq.prototype;_.aa.Ct=function(){return _.TZ(this,3)};_.aa.clearRect=function(){_.edq(this,14)};_.aa.Sc=function(){return _.TZ(this,10)};_.aa.Qc=function(){return _.TZ(this,16)};_.aa.hasAttributes=function(){return _.SZ(this,19)};
ZSq.prototype.getDescriptor=function(){var a=$Sq;a||($Sq=a=_.idq(ZSq,{0:{name:"LatLng",fullName:"location.unified.LatLng"},1:{name:"latitude_e7",Oi:15,type:Number},2:{name:"longitude_e7",Oi:15,type:Number}}));return a};ZSq.getDescriptor=ZSq.prototype.getDescriptor;aTq.prototype.getDescriptor=function(){var a=bTq;a||(bTq=a=_.idq(aTq,{0:{name:"LatLngRect",fullName:"location.unified.LatLngRect"},1:{name:"lo",Oi:11,type:ZSq},2:{name:"hi",Oi:11,type:ZSq}}));return a};aTq.getDescriptor=aTq.prototype.getDescriptor;
cTq.prototype.getDescriptor=function(){var a=dTq;a||(dTq=a=_.idq(cTq,{0:{name:"FieldOfView",fullName:"location.unified.FieldOfView"},1:{name:"field_of_view_x_degrees",Oi:2,type:Number},2:{name:"field_of_view_y_degrees",Oi:2,type:Number},3:{name:"screen_width_pixels",Oi:5,type:Number}}));return a};cTq.getDescriptor=cTq.prototype.getDescriptor;
eTq.prototype.getDescriptor=function(){var a=fTq;a||(fTq=a=_.idq(eTq,{0:{name:"FeatureIdProto",fullName:"location.unified.FeatureIdProto"},1:{name:"cell_id",Oi:6,type:String},2:{name:"fprint",Oi:6,type:String}}));return a};eTq.getDescriptor=eTq.prototype.getDescriptor;
gTq.prototype.getDescriptor=function(){var a=hTq;a||(hTq=a=_.idq(gTq,{0:{name:"ActivityRecord",fullName:"location.unified.ActivityRecord"},1:{name:"type",Oi:14,defaultValue:0,lba:{IN_VEHICLE:0,ON_BICYCLE:1,ON_FOOT:2,STILL:3,UNKNOWN:4,TILTING:5,EXITING_VEHICLE:6,WALKING:7,RUNNING:8,OFF_BODY:9,TRUSTED_GAIT:10,FLOOR_CHANGE:11,ON_STAIRS:12,ON_ESCALATOR:13,IN_ELEVATOR:14,SLEEPING:15,IN_ROAD_VEHICLE:16,IN_RAIL_VEHICLE:17,IN_TWO_WHEELER_VEHICLE:18,IN_FOUR_WHEELER_VEHICLE:19,IN_CAR:20,IN_BUS:21,EXPERIMENTAL_EXTRA_PERSONAL_VEHICLE:-1E3},
type:iTq},2:{name:"confidence",Oi:5,type:Number}}));return a};gTq.getDescriptor=gTq.prototype.getDescriptor;jTq.prototype.getDescriptor=function(){var a=kTq;a||(kTq=a=_.idq(jTq,{0:{name:"PersonalizedLocationAttributes",fullName:"location.unified.PersonalizedLocationAttributes"},4:{name:"pp_supporting_days",Oi:5,type:Number},5:{name:"pp_supporting_weeks",Oi:5,type:Number},10:{name:"supporting_packed_ip_ranges",repeated:!0,Oi:12,type:String}}));return a};jTq.getDescriptor=jTq.prototype.getDescriptor;
lTq.prototype.getDescriptor=function(){var a=mTq;a||(mTq=a=_.idq(lTq,{0:{name:"LocationAttributesProto",fullName:"location.unified.LocationAttributesProto"},2:{name:"heading_degrees",Oi:5,type:Number},3:{name:"bearing_degrees",Oi:5,type:Number},12:{name:"bearing_accuracy_degrees",Oi:5,type:Number},4:{name:"speed_kph",Oi:5,type:Number},13:{name:"speed_accuracy_kph",Oi:5,type:Number},5:{name:"tilt_degrees",Oi:5,type:Number},6:{name:"roll_degrees",Oi:5,type:Number},7:{name:"altitude_meters_from_ground",
Oi:1,type:Number},8:{name:"field_of_view",Oi:11,type:cTq},9:{name:"boarded_transit_vehicle_token",Oi:9,type:String},11:{name:"activity_record",repeated:!0,Oi:11,type:gTq},14:{name:"plm_type",Oi:14,defaultValue:0,lba:{PLMTYPE_UNKNOWN:0,PLMTYPE_FIRST:1,PLMTYPE_SECOND:2,PLMTYPE_THIRD:3,PLMTYPE_FOURTH:4,PLMTYPE_FIFTH:5,PLMTYPE_SIXTH:6,PLMTYPE_SEVENTH:7,PLMTYPE_EIGHTH:8,PLMTYPE_NINTH:9},type:nTq},15:{name:"inference",Oi:14,defaultValue:0,lba:{INFERENCE_NONE:0,INFERENCE_HULK_HEURISTIC:1,INFERENCE_HULK_CLASSIFIED:2,
INFERENCE_HULK_UNKNOWN:3,INFERENCE_PLM:4},type:oTq},16:{name:"manual_entry",Oi:14,defaultValue:0,lba:{MANUAL_ENTRY_NONE:0,MANUAL_ENTRY_UNKNOWN:1,MANUAL_ENTRY:2,MANUAL_ENTRY_DROPPED_PIN:3,MANUAL_ENTRY_HIGH_LEVEL:4,MANUAL_ENTRY_STALE:5,MANUAL_ENTRY_INSUFFICIENT_LOCATIONS:6},type:pTq},17:{name:"week_second_confidence",Oi:2,type:Number},18:{name:"ip_range_confidence",Oi:2,type:Number},19:{name:"carrier_ip_type",Oi:14,defaultValue:0,lba:{CARRIER_IP_UNKNOWN:0,CARRIER_IP_NOT_CARRIER:1,CARRIER_IP_MOBILE:2},
type:qTq},20:{name:"ads_confidence",Oi:2,type:Number},21:{name:"viewport_search_options",Oi:14,defaultValue:0,lba:{VIEWPORT_SEARCH_OPTIONS_UNSPECIFIED:0,VIEWPORT_SEARCH_OPTIONS_AROUND:1,VIEWPORT_SEARCH_OPTIONS_RESTRICT:2,VIEWPORT_SEARCH_OPTIONS_FILTER_ONLY:3,VIEWPORT_SEARCH_OPTIONS_FORCE_AROUND:4},type:rTq},10:{name:"device_location_ratio",Oi:2,type:Number},22:{name:"plm_source_location_count",Oi:5,type:Number},23:{name:"personalized_location_attributes",Oi:11,type:jTq}}));return a};
lTq.getDescriptor=lTq.prototype.getDescriptor;
sTq.prototype.getDescriptor=function(){var a=tTq;a||(tTq=a=_.idq(sTq,{0:{name:"SemanticPlace",fullName:"location.unified.SemanticPlace"},1:{name:"feature_id",Oi:11,type:eTq},2:{name:"gconcept_instance",repeated:!0,Oi:11,type:wTq},3:{name:"score",Oi:2,type:Number},4:{name:"confidence",Oi:14,defaultValue:0,lba:{UNKNOWN_CONFIDENCE:0,LOW_CONFIDENCE:1,MEDIUM_CONFIDENCE:2,HIGH_CONFIDENCE:3},type:uTq},5:{name:"source",Oi:14,defaultValue:0,lba:{UNKNOWN:0,HAPPY_HOUR:1,HULK_REAL_TIME:2,ANDROID_CONTEXT:3},type:vTq}}));
return a};sTq.getDescriptor=sTq.prototype.getDescriptor;wTq.prototype.getDescriptor=function(){var a=xTq;a||(xTq=a=_.idq(wTq,{0:{name:"GConceptInstanceProto",VPf:sTq,fullName:"location.unified.SemanticPlace.GConceptInstanceProto"},1:{name:"gconcept_id",Oi:9,type:String},2:{name:"prominence",Oi:14,defaultValue:0,lba:{NON_PRIMARY:0,PRIMARY:1E3},type:yTq}}));return a};wTq.getDescriptor=wTq.prototype.getDescriptor;
zTq.prototype.getDescriptor=function(){var a=ATq;a||(ATq=a=_.idq(zTq,{0:{name:"PresenceInterval",fullName:"location.unified.PresenceInterval"},1:{name:"start_offset_sec",Oi:4,type:String},2:{name:"duration_sec",Oi:4,type:String},3:{name:"confidence",Oi:13,type:Number}}));return a};zTq.getDescriptor=zTq.prototype.getDescriptor;
BTq.prototype.getDescriptor=function(){var a=CTq;a||(CTq=a=_.idq(BTq,{0:{name:"LocationDescriptor",fullName:"location.unified.LocationDescriptor"},1:{name:"role",Oi:14,defaultValue:0,lba:{UNKNOWN_ROLE:0,CURRENT_LOCATION:1,DEFAULT_LOCATION:2,QUERY:3,USER_SPECIFIED_FOR_REQUEST:4,HISTORICAL_QUERY:5,HISTORICAL_LOCATION:6,VIEWPORT:7,FUTURE_LOCATION:8,INVALID_LOCATION:9,EXPERIMENTAL_LOCATION:10,CURRENT_CONTEXT:11,FINAL_VIEWPORT:12,GLS_FINAL_VIEWPORT:13,PLAYABILITY_LOCATION:14,WILDCARD_ROLE:-1},type:USq},
2:{name:"producer",Oi:14,defaultValue:0,lba:{UNKNOWN_PRODUCER:0,LOGGED_IN_USER_SPECIFIED:1,PREF_L_FIELD_ADDRESS:2,IP_ADDRESS:3,IP_ADDRESS_REALTIME:42,IP_ADDRESS_SECONDARY:83,GOOGLE_HOST_DOMAIN:4,RQUERY:5,SQUERY:6,QUERY_LOCATION_OVERRIDE_PRODUCER:41,QREF:44,DEVICE_LOCATION:12,LEGACY_NEAR_PARAM:11,CARRIER_COUNTRY:17,CLIENT_SPECIFIED_JURISDICTION_COUNTRY:54,DECODED_FROM_UNKNOWN_ROLE_PRODUCER:68,SHOWTIME_ONEBOX:7,LOCAL_UNIVERSAL:8,SEARCH_TOOLBELT:13,MOBILE_FE_HISTORY:14,GWS_MOBILE_HISTORY_ZWIEBACK:34,
MOBILE_SELECTED:15,PARTNER:16,WEB_SEARCH_RESULTS_PAGE_SHARED:18,WEB_SEARCH_PREFERENCES_PAGE:20,MAPS_FRONTEND:21,PRODUCT_SEARCH_FRONTEND:22,ADS_CRITERIA_ID:23,MOBILE_APP:24,QUERY_HISTORY_INFERRED:25,QUERY_HISTORY_INFERRED_ALTERNATE:59,GMAIL_THEME:26,IGOOGLE:27,CALENDAR:28,SMS_SEARCH:29,LEGACY_GL_PARAM:30,LEGACY_PARTNER_GL_PARAM:31,LEGACY_GL_COOKIE:35,GWS_JURISDICTION_COUNTRY:64,CIRCULARS_FRONTEND:33,SHOPPING_SEARCH_API:36,OZ_FRONTEND:37,ADS_GEO_PARAM:38,ADS_PARTNER_GEO_PARAM:39,DEFAULT_LOCATION_OVERRIDE_PRODUCER:32,
VIEWPORT_PARAMS:40,GAIA_LOCATION_HISTORY:43,STICKINESS_PARAMS:45,TURN_BY_TURN_NAVIGATION_REROUTE:46,SNAP_TO_PLACE_IMPLICIT:47,SNAP_TO_PLACE_EXPLICIT:48,HULK_USER_PLACES_CONFIRMED:49,HULK_USER_PLACES_INFERRED:50,TACTILE_NEARBY_PARAM:52,MAPS_ACTIVITY:55,IP_ADDRESS_ALTERNATE:53,DIRECTIONS_START_POINT:56,SEARCH_ALONG_ROUTE:57,SNAP_TO_ROUTE:58,GOOGLE_MY_BUSINESS:60,BAD_DEVICE_LOCATION:61,GMM_QUANTIZED_DEVICE_LOCATION:62,GWS_HISTORY_GAIA:63,CONTEXT_MANAGER_FORECAST:65,GMM_HEATMAP_AREA:66,NEWS:67,SHIPPING_ADDRESS:69,
DEVICE_CONTEXT:70,TRAVEL_STATE_INTENT:71,HULK_ROUTINES:72,WILDCARD_PRODUCER:-1,LEGACY_TOOLBAR_HEADER:9,LEGACY_MOBILE_FRONTEND_GLL:10,LEGACY_MOBILE_FRONTEND_NEAR:19,ABLATED_PRODUCER:73,OOLONG_REALTIME_CACHE:74,OOLONG_REALTIME_CACHE_ALTERNATE:76,DIRECTIONS_WAYPOINT:75,ADS_FINAL_VIEWPORT:77,SEARCH_REGION_SETTINGS_COUNTRY:78,ASSISTANT_DERIVED:79,OOLONG_DEFAULT_LOCATION:80,ADS_GLS_FINAL_VIEWPORT:81,STORE_SELECTOR:82},type:VSq},3:{name:"timestamp",Oi:3,type:String},4:{name:"loc",Oi:9,type:String},5:{name:"latlng",
Oi:11,type:ZSq},6:{name:"latlng_span",Oi:11,type:ZSq},14:{name:"rect",Oi:11,type:aTq},7:{name:"radius",Oi:2,type:Number},8:{name:"confidence",Oi:5,defaultValue:100,type:Number},10:{name:"feature_id",Oi:11,type:eTq},26:{name:"additional_feature_id",Oi:11,type:eTq},16:{name:"mid",Oi:4,type:String},17:{name:"level_feature_id",Oi:11,type:eTq},18:{name:"level_number",Oi:2,type:Number},11:{name:"language",Oi:9,type:String},9:{name:"provenance",Oi:14,defaultValue:0,lba:{UNREMARKABLE:0,TOOLBAR:1,MOBILE_FE:2,
LEGACY_MOBILE_FRONTEND_GLL_PARAM:3,MAPS_FRONTEND_IL_DEBUG_IP:4,LEGACY_MOBILE_FRONTEND_NEAR_PARAM:5,GWS_MOBILE_CLIENT:6,GWS_MOBILE_CLIENT_ESSENTIAL_ONLY:12,XFF_HEADER:7,XGEO_HEADER:8,LEGACY_GEO_POSITION_HEADER:9,ASSISTANT_SETTINGS_FOR_CURRENT_DEVICE:10,ASSISTANT_DEVICE_PROPERTIES:11,FORWARDED_FROM_PROXY:13,EVAL_UNIQUE_SELECTED_USER_LOCATION:101,EVAL_BASE_UNIQUE_SELECTED_USER_LOCATION:102,EVAL_EXP_UNIQUE_SELECTED_USER_LOCATION:103,PERSONAL_LOCATION_MODEL_QUERY_ONLY:200},type:WSq},12:{name:"historical_role",
Oi:14,defaultValue:0,lba:{UNKNOWN_ROLE:0,CURRENT_LOCATION:1,DEFAULT_LOCATION:2,QUERY:3,USER_SPECIFIED_FOR_REQUEST:4,HISTORICAL_QUERY:5,HISTORICAL_LOCATION:6,VIEWPORT:7,FUTURE_LOCATION:8,INVALID_LOCATION:9,EXPERIMENTAL_LOCATION:10,CURRENT_CONTEXT:11,FINAL_VIEWPORT:12,GLS_FINAL_VIEWPORT:13,PLAYABILITY_LOCATION:14,WILDCARD_ROLE:-1},type:USq},13:{name:"historical_producer",Oi:14,defaultValue:0,lba:{UNKNOWN_PRODUCER:0,LOGGED_IN_USER_SPECIFIED:1,PREF_L_FIELD_ADDRESS:2,IP_ADDRESS:3,IP_ADDRESS_REALTIME:42,
IP_ADDRESS_SECONDARY:83,GOOGLE_HOST_DOMAIN:4,RQUERY:5,SQUERY:6,QUERY_LOCATION_OVERRIDE_PRODUCER:41,QREF:44,DEVICE_LOCATION:12,LEGACY_NEAR_PARAM:11,CARRIER_COUNTRY:17,CLIENT_SPECIFIED_JURISDICTION_COUNTRY:54,DECODED_FROM_UNKNOWN_ROLE_PRODUCER:68,SHOWTIME_ONEBOX:7,LOCAL_UNIVERSAL:8,SEARCH_TOOLBELT:13,MOBILE_FE_HISTORY:14,GWS_MOBILE_HISTORY_ZWIEBACK:34,MOBILE_SELECTED:15,PARTNER:16,WEB_SEARCH_RESULTS_PAGE_SHARED:18,WEB_SEARCH_PREFERENCES_PAGE:20,MAPS_FRONTEND:21,PRODUCT_SEARCH_FRONTEND:22,ADS_CRITERIA_ID:23,
MOBILE_APP:24,QUERY_HISTORY_INFERRED:25,QUERY_HISTORY_INFERRED_ALTERNATE:59,GMAIL_THEME:26,IGOOGLE:27,CALENDAR:28,SMS_SEARCH:29,LEGACY_GL_PARAM:30,LEGACY_PARTNER_GL_PARAM:31,LEGACY_GL_COOKIE:35,GWS_JURISDICTION_COUNTRY:64,CIRCULARS_FRONTEND:33,SHOPPING_SEARCH_API:36,OZ_FRONTEND:37,ADS_GEO_PARAM:38,ADS_PARTNER_GEO_PARAM:39,DEFAULT_LOCATION_OVERRIDE_PRODUCER:32,VIEWPORT_PARAMS:40,GAIA_LOCATION_HISTORY:43,STICKINESS_PARAMS:45,TURN_BY_TURN_NAVIGATION_REROUTE:46,SNAP_TO_PLACE_IMPLICIT:47,SNAP_TO_PLACE_EXPLICIT:48,
HULK_USER_PLACES_CONFIRMED:49,HULK_USER_PLACES_INFERRED:50,TACTILE_NEARBY_PARAM:52,MAPS_ACTIVITY:55,IP_ADDRESS_ALTERNATE:53,DIRECTIONS_START_POINT:56,SEARCH_ALONG_ROUTE:57,SNAP_TO_ROUTE:58,GOOGLE_MY_BUSINESS:60,BAD_DEVICE_LOCATION:61,GMM_QUANTIZED_DEVICE_LOCATION:62,GWS_HISTORY_GAIA:63,CONTEXT_MANAGER_FORECAST:65,GMM_HEATMAP_AREA:66,NEWS:67,SHIPPING_ADDRESS:69,DEVICE_CONTEXT:70,TRAVEL_STATE_INTENT:71,HULK_ROUTINES:72,WILDCARD_PRODUCER:-1,LEGACY_TOOLBAR_HEADER:9,LEGACY_MOBILE_FRONTEND_GLL:10,LEGACY_MOBILE_FRONTEND_NEAR:19,
ABLATED_PRODUCER:73,OOLONG_REALTIME_CACHE:74,OOLONG_REALTIME_CACHE_ALTERNATE:76,DIRECTIONS_WAYPOINT:75,ADS_FINAL_VIEWPORT:77,SEARCH_REGION_SETTINGS_COUNTRY:78,ASSISTANT_DERIVED:79,OOLONG_DEFAULT_LOCATION:80,ADS_GLS_FINAL_VIEWPORT:81,STORE_SELECTOR:82},type:VSq},15:{name:"historical_prominence",Oi:5,type:Number},19:{name:"attributes",Oi:11,type:lTq},20:{name:"diagnostic_info",Oi:9,type:String},21:{name:"semantic",repeated:!0,Oi:14,defaultValue:0,lba:{SEMANTIC_UNKNOWN:0,SEMANTIC_REROUTE_SOURCE:1,SEMANTIC_REROUTE_PROPOSED:2,
SEMANTIC_REROUTE_TAKEN:3,SEMANTIC_HOME:4,SEMANTIC_WORK:5,SEMANTIC_ONBOARD_TRANSIT:6,SEMANTIC_MAPS_SEARCH:7,SEMANTIC_FREQUENT_PLACE:8,SEMANTIC_OTHER:9},type:XSq},22:{name:"semantic_place",repeated:!0,Oi:11,type:sTq},24:{name:"presence_interval",repeated:!0,Oi:11,type:zTq},25:{name:"permission_granularity",Oi:14,defaultValue:0,lba:{PERMISSION_GRANULARITY_UNKNOWN:0,PERMISSION_GRANULARITY_COARSE:1,PERMISSION_GRANULARITY_FINE:2},type:YSq}}));return a};BTq.getDescriptor=BTq.prototype.getDescriptor;var DTq=function(a,b){this.Ba=!!a;this.Aa=!!b};_.Th(DTq,_.Ycq);DTq.prototype.oa=function(a,b){const c=new ETq;c.parse(a,b.toString(),this.Ba)||c.getError()};DTq.prototype.serialize=function(a){const b=new FTq;GTq(this,a,b);return b.toString()};
var GTq=function(a,b,c){_.Zcq(b.getDescriptor()).forEach(function(d){if(b.has(d)){var e=_.hdq(b,d.oa);for(let f=0;f<e;++f){c.append(d.getName());d.Aa==11||d.Aa==10?(c.append(" {"),HTq(c),c.indent()):c.append(": ");ITq(this,b.get(d,f),d,c);if(d.Aa==11||d.Aa==10)c.oa-=2,c.append("}");HTq(c)}}},a);_.bdq(b,function(d,e){JTq(this,d,e,c)},a)},JTq=function(a,b,c,d){if(c!=null)if(Array.isArray(c))c.forEach(function(e){JTq(this,b,e,d)},a);else{if(_.lf(c)){d.append(b);d.append(" {");HTq(d);d.indent();if(c instanceof
_.RZ)GTq(a,c,d);else for(const e in c)JTq(a,_.aDa(e),c[e],d);d.oa-=2;d.append("}")}else typeof c==="string"&&(c=HSq(c)),d.append(b),d.append(": "),d.append(c);HTq(d)}},ITq=function(a,b,c,d){switch(c.Aa){case 1:case 2:case 3:case 4:case 5:case 13:case 6:case 7:case 8:case 15:case 16:case 17:case 18:d.append(b);break;case 12:case 9:b=HSq(b.toString());d.append(b);break;case 14:let e=!1;a.Aa||(_.wc(c.Ea,function(f,g){e||f!=b||(d.append(g),e=!0)}),e||_.wc(c.Ba,function(f,g){e||f!=b||(d.append(g),e=!0)}));
e&&!a.Aa||d.append(b.toString());break;case 10:case 11:GTq(a,b,d)}},FTq=function(){this.oa=0;this.Aa=[];this.Ba=!0};FTq.prototype.toString=function(){return this.Aa.join("")};FTq.prototype.indent=function(){this.oa+=2};FTq.prototype.append=function(a){if(this.Ba){for(let b=0;b<this.oa;++b)this.Aa.push(" ");this.Ba=!1}this.Aa.push(String(a))};var HTq=function(a){a.Aa.push("\n");a.Ba=!0},LTq=function(a){this.Ca=a;this.oa=0;this.Ba=a;this.Aa={type:KTq,value:null}};LTq.prototype.getCurrent=function(){return this.Aa};
var KTq=/$ end $/,MTq=/$ bad $/,NTq=/^-?[a-zA-Z][a-zA-Z0-9_]*/,OTq=/^-?(0[0-7]+|0x[0-9a-f]+|([.][0-9]+|(0|[1-9][0-9]*)([.][0-9]*)?)(e[+-]?[0-9]+)?f?)/i,PTq=/^#.*/,QTq=RegExp('^"([^"\\\\]|\\\\.)*"'),RTq=/^\s/,STq={END:KTq,k0e:MTq,khf:NTq,NUMBER:OTq,C3e:PTq,hsf:/^{/,p3e:/^}/,jsf:/^</,r3e:/^>/,isf:/^\[/,q3e:/^\]/,STRING:QTq,w3e:/^:/,A3e:/^,/,nAf:/^;/,IMf:RTq};
LTq.prototype.next=function(){let a;for(;TTq(this);)if(a=this.getCurrent().type,a!=RTq&&a!=PTq)return!0;this.Aa={type:this.Ba.length==0?KTq:MTq,value:null};return!1};
var TTq=function(a){if(a.oa>=a.Ca.length)return!1;const b=a.Ba;let c=null;_.wja(STq,function(d){if(c||d==KTq)return!1;const e=d.exec(b);e&&e.index==0&&(c={type:d,value:e[0]});return!!c});if(c){if(a.Aa.type==OTq&&c.type==NTq)return!1;a.Aa=c;a.oa+=c.value.length;a.Ba=a.Ba.substring(c.value.length)}return!!c},ETq=function(){this.oa=this.Ou=null;this.Aa=!1};ETq.prototype.parse=function(a,b,c){this.Ou=null;this.Aa=!!c;this.oa=new LTq(b);this.oa.next();return UTq(this,a,"")};ETq.prototype.getError=function(){return this.Ou};
var UTq=function(a,b,c){for(;a.oa.getCurrent().value!=">"&&a.oa.getCurrent().value!="}"&&!VTq(a,KTq);)if(!WTq(a,b))return!1;if(c){if(!XTq(a,c))return!1}else VTq(a,KTq)||(a.Ou="Expected END token");return!0},ZTq=function(a,b,c){a=YTq(a,c);if(a===null)return!1;c.isRepeated()?b.add(c,a):b.set(c,a);return!0},$Tq=function(a){return/^-?0x/i.test(a)?16:/^-?0[0-7]/.test(a)?8:/[.ef]/i.test(a)?0:10},aUq=function(a){const b=$Tq(a);return b==0?parseFloat(a):parseInt(a,b)},YTq=function(a,b){switch(b.Aa){case 1:case 2:if(b=
bUq(a,NTq))if(b=/^-?inf(?:inity)?f?$/i.test(b)?Infinity*(_.ea(b,"-")?-1:1):/^nanf?$/i.test(b)?NaN:null,b!=null)return b;case 5:case 13:case 7:case 15:case 17:return(a=bUq(a,OTq))?aUq(a):null;case 3:case 4:case 6:case 16:case 18:a=bUq(a,OTq);if(!a)return null;if(b.Ba==Number)return aUq(a);b=$Tq(a);b!=10&&(a=_.iJa(a,b).toString(10));return a;case 8:b=bUq(a,NTq);if(!b)return null;switch(b){case "true":return!0;case "false":return!1;default:return a.Ou="Unknown type for bool: "+b,null}case 14:if(VTq(a,
OTq))return(a=bUq(a,OTq))?aUq(a):null;var c=bUq(a,NTq);if(!c)return null;b=b.Ea[c];return b==null?(a.Ou="Unknown enum value: "+c,null):b;case 12:case 9:if(c=bUq(a,QTq)){for(b=JSON.parse(c).toString();VTq(a,QTq);)c=bUq(a,QTq),b+=JSON.parse(c).toString();a=b}else a=null;return a}},dUq=function(a){cUq(a,":");if(cUq(a,"[")){for(;;){a.oa.next();if(cUq(a,"]"))break;if(!XTq(a,","))return!1}return!0}if(cUq(a,"<"))return UTq(a,null,">");if(cUq(a,"{"))return UTq(a,null,"}");a.oa.next();return!0},WTq=function(a,
b){var c=bUq(a,NTq);if(!c)return a.Ou="Missing field name",!1;var d=null;b&&(d=ESq(b.getDescriptor(),c.toString()));if(d==null){if(a.Aa)return dUq(a);a.Ou="Unknown field: "+c;return!1}if(d.Aa==11||d.Aa==10){cUq(a,":");a:{c=d;if(cUq(a,"<"))d=">";else{if(!XTq(a,"{")){b=!1;break a}d="}"}const e=new (c.Ba.prototype.getDescriptor().yNc);UTq(a,e,d)?(c.isRepeated()?b.add(c,e):b.set(c,e),b=!0):b=!1}if(!b)return!1}else{if(!XTq(a,":"))return!1;if(d.isRepeated()&&cUq(a,"["))for(;;){if(!ZTq(a,b,d))return!1;if(cUq(a,
"]"))break;if(!XTq(a,","))return!1}else if(!ZTq(a,b,d))return!1}cUq(a,",")||cUq(a,";");return!0},cUq=function(a,b){return a.oa.getCurrent().value==b?(a.oa.next(),!0):!1},bUq=function(a,b){if(!VTq(a,b))return a.Ou="Expected token type: "+b,null;b=a.oa.getCurrent().value;a.oa.next();return b},XTq=function(a,b){return cUq(a,b)?!0:(a.Ou='Expected token "'+b+'"',!1)},VTq=function(a,b){return a.oa.getCurrent().type==b};var eUq,fUq;eUq=new _.cC("h",6);fUq=new _.cC("n",10);
_.gUq=class{constructor(a,b){this.oa=eUq;this.Ba=a;this.Aa=b}write(a,b){if(QSq){var c=new MSq;c=_.Wg(c,1,1);c=_.Wg(c,2,12);c=_.Wg(c,9,b===2?12:6);if(a.timestamp){var d=String(NSq(a.timestamp).getTime()*1E3);_.Og(c,3,d)}if(a=a.coords){if(a.latitude&&a.longitude){d=a.latitude;var e=a.longitude,f=new JSq;_.Ah(f,1,Math.round(d*1E7));_.Ah(f,2,Math.round(e*1E7));_.Eb(c,JSq,5,f)}a.accuracy&&_.Xg(c,7,a.accuracy*1E3*.62);this.Ba&&(a.speed||a.heading)&&(d=new LSq,a.speed&&_.Ah(d,4,Math.round(a.speed*3.6)),
a.heading&&_.Ah(d,3,Math.round(a.heading)),_.Eb(c,LSq,19,d))}a=c.serialize();a=`${"j"}${"+"}${_.$h(a)}`;_.Ae.set(lSq(b),a,{P$:DSq(b===2?fUq:this.oa),path:"/",domain:void 0,secure:this.Aa})}else{c=new BTq;_.UZ(c,1,1);_.UZ(c,2,12);_.UZ(c,9,b===2?12:6);a.timestamp&&(d=c,e=String(NSq(a.timestamp).getTime()*1E3),_.UZ(d,3,e));if(a=a.coords)a.latitude&&a.longitude&&(d=a.latitude,e=a.longitude,f=new ZSq,_.UZ(f,1,Math.round(d*1E7)),_.UZ(f,2,Math.round(e*1E7)),_.UZ(c,5,f)),a.accuracy&&_.UZ(c,7,a.accuracy*1E3*
.62),this.Ba&&(a.speed||a.heading)&&(d=new lTq,a.speed&&_.UZ(d,4,Math.round(a.speed*3.6)),a.heading&&_.UZ(d,3,Math.round(a.heading)),_.UZ(c,19,d));a=c;a=(new DTq(!0,!0)).serialize(a);a=`${"a"}${"+"}${_.$h(a)}`;_.Ae.set(lSq(b),a,{P$:DSq(b===2?fUq:this.oa),path:"/",domain:void 0,secure:this.Aa})}}};var oSq,pSq,qSq;oSq=[{Lyb:54E4,timeoutMillis:3E4}];pSq=[{Lyb:15E3,timeoutMillis:3E4,enableHighAccuracy:!0},{Lyb:54E4,timeoutMillis:3E4}];qSq=[{Lyb:15E3,timeoutMillis:3E4},{Lyb:54E4,timeoutMillis:3E4}];_.hUq=class{constructor(a){this.ot=a}getCurrentPosition(a,b){const c=this;return _.y(function*(){let d;for(const e of rSq(b))try{return yield c.ot.getCurrentPosition(a,e.timeoutMillis,e)}catch(f){if(_.TSq(f).oa())throw f;d=f}throw d||Error("iw");})}};_.iUq=function(a,b){a.oa=!0;var c=a.Aa,d=_.sSq(b);_.Wg(c,3,d);a=a.Aa;b=b.getDetails();_.Eb(a,_.AMb,15,b)};_.jUq=function(a,b){a.oa=!0;_.wj(a.Aa,5,b)};_.kUq=function(a){a.oa=!0;_.Wg(a.Aa,4,1)};_.lUq=function(a,b){a.oa=!0;_.Wg(a.Aa,4,tSq(b))};_.mUq=function(a,b){a.oa=!0;_.Yg(a.Aa,9,!0);let c;(c=a.counters)==null||c.vme(b)};
_.nUq=class{constructor(a,b){this.jhc=a;this.counters=b;this.Aa=new _.FNb;this.oa=!1}flush(){const a=this;return _.y(function*(){if(a.oa){var b;(b=a.counters)==null||b.flush();a.jhc&&(b=_.Qd(a.Aa.Aa(),4),yield _.Qv([new _.mo(a.jhc,"show")],{data:{lpl:b}}));a.oa=!1}})}};_.xSq=class extends Error{constructor(a,b){super(b);this.code=a}};var oUq;_.n_=function(a){return _.Oi(a,1)};_.o_=function(a){var b=new oUq;return _.Wg(b,1,a)};oUq=class extends _.m{constructor(a){super(a)}getDetails(){return _.n(this,_.AMb,2)}};var pUq;pUq=function(a){return _.y(function*(){var b=Date.now();try{const d=yield a.Ea.zDc(),e=Date.now()-b;var c=a.logger;c.oa=!0;_.wj(c.Aa,6,e);return wSq(d)}catch(d){throw d instanceof _.xSq&&d.code===1||(c=Date.now()-b,b=a.logger,b.oa=!0,_.wj(b.Aa,6,c)),d;}})};
_.qUq=class{constructor(a,b){this.Ea=a;this.logger=b;this.oa=this.Da=0;this.Ba=this.Ca=null;this.Aa=_.o_(0);this.Aa=_.o_(0)}Rba(){this.Ca||(this.Ca=pUq(this));return this.Ca}Twa(){this.Ba||(this.Ba=this.Ea.zDc().then(wSq));return this.Ba}lta(){const a=this;return _.y(function*(){a.Aa=yield a.Rba();a.oa=1;a.Da=Date.now()})}XYa(a=Date.now()-this.Da){const b=this;return _.y(function*(){_.n_(b.Aa);b.oa=2})}WYa(a,b=Date.now()-this.Da){const c=this;return _.y(function*(){if(_.n_(c.Aa)===0||c.oa!==1)c.oa=
2;else{c.oa=2;var d=yield c.Twa();_.n_(d)!==0&&uSq(_.n_(d))&&b<500&&(c.Aa=_.o_(3))}})}lLa(){return uSq(_.n_(this.Aa))&&this.oa===2}};_.rUq=new _.io;var sUq,tUq,uUq,vUq,wUq,xUq,yUq,zUq,BUq,CUq;sUq=class{Rba(){return _.y(function*(){return _.o_(0)})}Twa(){return _.y(function*(){return _.o_(0)})}lta(){return _.y(function*(){})}XYa(){return _.y(function*(){})}WYa(){return _.y(function*(){})}lLa(){return!1}};tUq=function(a){return a.oa?a.Aa:a.Ba};uUq=function(a){return _.y(function*(){a.oa=!0;a.Ca!==void 0&&(yield a.Aa.lta(a.Ca))})};vUq=function(a){return _.y(function*(){!a.oa&&a.Da.EJc()&&(yield uUq(a))})};
wUq=function(a){return _.y(function*(){yield vUq(a);try{return yield tUq(a).Rba()}catch(b){return!a.oa&&ySq(b)?(yield uUq(a),a.Aa.Rba()):_.o_(0)}})};xUq=function(a){return _.y(function*(){if(!a.oa){const b=yield a.Ba.Rba().then(void 0,()=>_.o_(0));a.Da.vAd(b)}})};yUq=function(a){return _.y(function*(){if(!a.oa){const b=yield a.Ba.Twa().then(void 0,()=>_.o_(0));a.Da.uAd(b);yield vUq(a)}})};zUq=function(a){return _.y(function*(){a.oa||(yield a.Ba.Twa().then(void 0,()=>_.o_(0)),yield vUq(a))})};
_.AUq=class{constructor(a,b,c,d){this.Da=a;this.Ba=b;this.logger=c;this.oa=!1;this.Aa=d||new sUq}Rba(){const a=this;return _.y(function*(){const b=yield wUq(a);if(a.oa)if(a.Da.EJc()){var c=a.logger;c.oa=!0;_.Wg(c.Aa,7,2)}else c=a.logger,c.oa=!0,_.Wg(c.Aa,7,1);else c=a.logger,c.oa=!0,_.Wg(c.Aa,7,3);_.iUq(a.logger,b);return b})}Twa(){const a=this;return _.y(function*(){yield vUq(a);try{return yield tUq(a).Twa()}catch(b){return!a.oa&&ySq(b)?(yield uUq(a),a.Aa.Twa()):_.o_(0)}})}lta(){const a=this;return _.y(function*(){yield xUq(a);
yield a.Rba();try{yield tUq(a).lta(Date.now())}catch(b){!a.oa&&ySq(b)&&(yield uUq(a),yield a.Aa.lta(Date.now()))}a.Ca=Date.now()})}XYa(a=Date.now()-this.Ca){const b=this;return _.y(function*(){_.kUq(b.logger);_.jUq(b.logger,a);yield yUq(b);try{yield tUq(b).XYa(a)}catch(c){!b.oa&&ySq(c)&&(yield uUq(b),yield b.Aa.XYa(a))}})}WYa(a,b=Date.now()-this.Ca){const c=this;return _.y(function*(){_.lUq(c.logger,a.code);_.jUq(c.logger,b);yield zUq(c);try{yield tUq(c).WYa(a,b)}catch(d){!c.oa&&ySq(d)&&(yield uUq(c),
yield c.Aa.WYa(a,b))}})}lLa(){return tUq(this).lLa()}};BUq=function(a){return a.oa?a.Aa:a.Ba};CUq=function(a){return _.y(function*(){let b;try{b=yield BUq(a).Rba()}catch(c){return ySq(c)?(a.oa=!0,[yield a.Aa.Rba(),1]):[_.o_(0),3]}return _.n_(b)===1&&PSq?(a.oa=!0,[yield a.Aa.Rba(),2]):[b,3]})};
_.DUq=class{constructor(a,b,c){this.Ba=a;this.logger=b;this.oa=!1;this.Aa=c||new sUq}Rba(){const a=this;return _.y(function*(){const [b,c]=yield CUq(a);var d=a.logger;d.oa=!0;_.Wg(d.Aa,7,c);_.iUq(a.logger,b);return b})}Twa(){const a=this;return _.y(function*(){try{return yield a.Ba.Twa()}catch(b){return _.o_(0)}})}lta(){const a=this;return _.y(function*(){yield a.Rba();try{yield BUq(a).lta(Date.now())}catch(c){if(ySq(c)){a.oa=!0;var b=a.logger;b.oa=!0;_.Wg(b.Aa,7,1);yield a.Aa.lta(Date.now())}}a.Ca=
Date.now()})}XYa(a=Date.now()-this.Ca){const b=this;return _.y(function*(){_.kUq(b.logger);_.jUq(b.logger,a);yield BUq(b).XYa(a)})}WYa(a,b=Date.now()-this.Ca){const c=this;return _.y(function*(){_.lUq(c.logger,a.code);_.jUq(c.logger,b);yield BUq(c).WYa(a,b)})}lLa(){return BUq(this).lLa()}};var EUq=function(a){a.storage.set("iks",0);a.storage.set("sr",0);a.sum=0;a.storage.set("lltsa",Date.now())},FUq=function(a,b,c,d){const e=Date.now();c=c>500;(b||c)&&a.storage.set("lstot",e);(c||a.sum<0&&b||a.sum>0&&!b)&&a.storage.set("lltsa",e);switch(d){case 0:a.oa=e;a.storage.set("ltp",a.oa);break;case 1:case 5:b?a.sum++:a.sum--;a.storage.set("sr",a.sum);if(a.sum<-1||1<a.sum)a.Aa=!0,a.storage.set("iks",Number(a.Aa));a.oa=e;a.storage.set("ltp",a.oa)}},GUq=class{constructor(a,b){this.storage=a;this.logger=
b;this.oa=Number(this.storage.get("ltp"));this.sum=Number(this.storage.get("sr"));this.Aa=!!this.storage.get("iks")}lta(a){this.storage.set("loot",a);Number(this.storage.get("lltsa"))||this.storage.set("lltsa",a)}},HUq=function(a,b=Date.now()){if(a.oa){a=a.oa;a.oa||(a.oa=b,a.storage.set("ltp",a.oa));var c=Number(a.storage.get("lltsa"));var d=Number(a.storage.get("loot"));if(c=!c||!d||a.sum<=0?!1:d-c>864E5)d=a.logger,d.oa=!0,_.Yg(d.Aa,8,!0);a.oa&&Date.now()-a.oa>864E5&&!c&&(a.sum=0,a.storage.set("sr",
a.sum),a.Aa=!0,a.storage.set("iks",Number(a.Aa)));b=a.Aa?a.sum<-1?3:a.sum>1?2:b-Number(a.storage.get("lstot"))<6048E5?1:b-Number(a.storage.get("loot"))<6048E5?6:5:0}else b=0;return b},BSq=class{constructor(a,b){this.Ba=!1;this.oa=a?new GUq(a,b):null;this.Aa=0}XYa(a){const b=this;return _.y(function*(){let c=b.Aa;if(b.Aa===3||b.Aa===6)c=0,b.oa&&EUq(b.oa);a>500&&(b.Ba=!0);b.oa&&FUq(b.oa,!0,a,c)})}WYa(a,b){const c=this;return _.y(function*(){let d=!0;a.oa()&&(d=!1);let e=c.Aa;if(c.Aa===2&&!d||c.Aa===
3&&d||b>500&&c.Aa===6)e=0,c.oa&&EUq(c.oa);b>500&&(c.Ba=!0);c.oa&&FUq(c.oa,d,b,e)})}lLa(){return this.Ba}Rba(){return Promise.resolve(_.o_(HUq(this)))}Twa(){return Promise.resolve(_.o_(HUq(this)))}lta(a){this.Aa=HUq(this,a);this.oa&&this.oa.lta(a);return Promise.resolve()}};_.IUq=class{zDc(){return _.y(function*(){var a=_.Tb().oa;a=yield _.Ze(_.c1a,a);return a!=null&&a.isAvailable()&&a.B$()?a.Xqa().then(zSq,ASq):Promise.reject(new _.xSq(1,"Silk API not available."))})}};_.JUq=class{constructor(a){this.storage=a}EJc(){return this.storage.get("upa")===1}vAd(a){_.n_(a)!==1&&this.storage.remove("upa")}uAd(a){_.n_(a)===1&&this.storage.set("upa",1)}};_.KUq=class{EJc(){return!1}vAd(){}uAd(){}};
var LUq=function(a){switch(a){case "granted":return 1;case "denied":return 2;case "prompt":return 3;default:return 0}},MUq=class{zDc(){return _.y(function*(){let a,b;if(!((a=navigator)==null?0:(b=a.permissions)==null?0:b.query))throw new _.xSq(1,"HTML5 permissions API missing");try{const d=yield navigator.permissions.query({name:"geolocation"});if(!d)throw new _.xSq(2,"HTML5 geolocation permissions API returned null or undefined.");var c=new _.RRq;return _.Wg(c,4,LUq(d.state))}catch(d){throw d instanceof
TypeError?new _.xSq(1,"HTML5 geolocation permissions API missing"):d instanceof _.xSq?d:new _.xSq(4,`The HTML5 geolocation permissions API returned an unknown error: ${d}`);}})}};_.go(_.rUq,class{create(){return new MUq}});
}catch(e){_._DumpException(e)}
try{
var hWq,iWq;hWq=function(a){return{Y6:Number(a.get("backoff")),XKc:Number(a.get("last-rej"))}};iWq=function(a,{Y6:b,XKc:c}){a.set("backoff",b)&&a.set("last-rej",c)};
_.jWq=class{constructor(a,b){this.storage=a;this.oa=b}g0a(){const a=this;return _.y(function*(){if(!a.storage)return[2];const {Y6:b,XKc:c}=hWq(a.storage),d=Number(a.oa.Aa());return b&&c&&Date.now()-c<Math.min(b,d)?[1]:[0,2]})}KDb(a,b){if(this.storage)if(a){var c=this.storage;c.remove("backoff");c.remove("last-rej")}else b&&({Y6:a}=hWq(this.storage),a?c=Math.max(a,Math.min(Number(this.oa.Ba())*a,Number(this.oa.Aa()))):c=Number(this.oa.Ca()),iWq(this.storage,{Y6:c,XKc:Date.now()}))}};_.kWq=class{constructor(a,b,c){this.storage=a;this.ei=b;this.oa=c}g0a(){const a=this;return _.y(function*(){if(!_.mla())return[7];if(_.ca.lpt)return[5];if(!a.storage)return[2];var b=a.storage.get("last-ei");b=b instanceof Array?b:[];if(b.indexOf(a.ei)!==-1)b=!1;else{for(b.push(a.ei);b.length>3;)b.shift();a.storage.set("last-ei",b);b=!0}if(!b)return[6];b=yield a.oa.g0a();const [c]=b;c===0&&(_.ca.lpt=!0);return b})}KDb(a,b){this.oa.KDb(a,b)}};
}catch(e){_._DumpException(e)}
try{
_.gWq=_.w("KHourd",[]);
}catch(e){_._DumpException(e)}
try{
_.uVq=_.w("pjDTFb",[_.fr]);
}catch(e){_._DumpException(e)}
try{
var PVq,SVq,TVq;_.NVq=function(){let a;try{a=window.performance.now()}catch(b){return}return _.Ivd((new _.Sr).setSeconds(Math.floor(a/1E3)),a%1E3*1E6)};_.OVq=function(a){switch(a){case 0:return 1;case 1:return 3;case 2:return 4;case 3:return 5;case 5:return 6;case 6:return 7;case 7:return 8;case 8:return 9;case 9:return 10;case 100:return 100;case 101:return 101;default:return 0}};PVq=function(a){a.oa&&google.c.q("aft",()=>{(0,_.Fe)(()=>{a.flush()})})};
_.RVq=function(a,b,c,d,e,f,g=!0){return window.btoa?new QVq(a,c,b,d,e,f,g):null};SVq=function(){const a=_.ah().location;return{state:_.ah().history.state,url:a.pathname+a.search+a.hash}};TVq=function(a){return _.y(function*(){var b=_.Tb().oa;const c=yield _.Ze(_.uVq,b),d=yield _.Ze(_.qr,b);b=_.z(a,76)?yield _.Ze(_.j5a,b):void 0;return{Ana:c,kc:d,oz:b}})};_.VVq=function(a,b){const c=_.z(a,74)?TVq(a):void 0;return new UVq(a,b,c)};
_.WVq=class extends _.m{constructor(a){super(a)}Ca(){return _.Mi(this,1)}Aa(){return _.Mi(this,2)}Ba(){return _.Ni(this,3)}};_.XVq=class extends _.m{constructor(a){super(a)}qp(){return _.z(this,79)}};_.XVq.prototype.ob="C4mkuf";_.YVq=class{constructor(a){this.error=a}};var $Vq=function(a,[b,c]){return _.y(function*(){var d=a.logger;d.oa=!0;var e=_.Wg(d.Aa,1,_.OVq(b)),f=_.NVq();_.Eb(e,_.Sr,12,f);let g;(g=d.counters)==null||g.ume(b);if(b===0)return a.prompt(c);yield ZVq(a);PVq(a.logger);return new _.YVq(null)})},ZVq=function(a){return _.y(function*(){const b=yield a.Tna.Rba();_.n_(b)!==3&&_.n_(b)!==6||_.nSq()})},bWq=function(a,b){return _.y(function*(){yield a.Tna.XYa();var c=b.JKb;const d=_.Oi(a.config,62)||0;a.Ba.write(c,d);c=(c=b.pyd)?c===2:a.Tna.lLa();a.Hjb.KDb(!0,
c);c&&_.mUq(a.logger,!0);yield a.logger.flush();c&&(yield aWq(a.Aa));return new _.YVq(null)})},cWq=function(a,b){return _.y(function*(){const c=_.TSq(b);yield a.Tna.WYa(c);_.TSq(c).oa()&&_.nSq();const d=!c.oa(),e=a.Tna.lLa();a.Hjb.KDb(d,e);e&&_.mUq(a.logger,d);yield a.logger.flush();yield a.Tna.Twa();return new _.YVq(new _.p_(c.code,c.message))})},QVq=class{constructor(a,b,c,d,e,f,g=!0){this.config=a;this.Hjb=b;this.logger=c;this.Tna=d;this.oa=e;this.Aa=f;this.Ba=new _.gUq(!0,g)}start(){const a=this;
return _.y(function*(){a.Aa.prepare();if(!_.kSq(_.Oi(a.config,62))){var b=a.logger;b.oa=!0;_.Yg(b.Aa,2,!0)}b=yield a.Hjb.g0a();return $Vq(a,b)})}prompt(a){const b=this;return _.y(function*(){if(_.Zg(b.config,79)&&_.n_(yield b.Tna.Rba())!==2)return PVq(b.logger),new _.YVq(null);yield b.Tna.lta();PVq(b.logger);try{if(_.Oi(b.config,83)===0){const d=yield b.oa.getCurrentPosition(a,3E4);return bWq(b,d)}const c=yield(new _.hUq(b.oa)).getCurrentPosition(a,_.Oi(b.config,83));return bWq(b,c)}catch(c){return cWq(b,
c)}})}};_.dWq=class{g0a(){return _.y(function*(){return[0,2]})}KDb(){}};var aWq=function(a){return _.y(function*(){if(a.oa)return eWq(a,a.oa);fWq(a)})},eWq=function(a,b){return _.y(function*(){if(_.z(a.config,21)){const c=yield b,d=c.Ana.oa(new Map([["sei",a.ei],["dlnr","1"]]));if(c.oz)try{yield c.oz.transition(d.toString());return}catch(e){_.ee(Error("jw`"+e))}c.kc.navigateTo(d,!1)}})},fWq=function(a){if(_.z(a.config,21)&&SVq().url===a.Aa){const b=a.ei;google.x({id:"udla"},()=>{google.nav.search({dlnr:"1",sei:b,devloc:null},!0)})}},UVq=class{constructor(a,b,c){this.config=
a;this.ei=b;this.oa=c;this.Aa=null}prepare(){this.oa||(this.Aa=SVq().url)}};
}catch(e){_._DumpException(e)}
try{
_.SRq=class extends _.m{constructor(a){super(a)}Ea(){return _.Rd(this,2)}Ba(){return _.Ei(this,2)}Da(){return _.Rj(this,3)}Aa(){return _.Zg(this,3)}Ka(){return _.Rd(this,4)}Ca(){return _.Ei(this,4)}};_.TRq=class extends _.m{constructor(a){super(a)}avb(){return _.rj(this,1)}ANb(){return _.bk(this,1)}getOptions(){return _.n(this,_.SRq,2)}setOptions(a){return _.Eb(this,_.SRq,2,a)}};_.TRq.prototype.Aa=_.Mb([0,_.H,[0,1,_.tk,_.D,_.tk]]);
}catch(e){_._DumpException(e)}
try{
var UUq,WUq,VUq,ZUq,YUq,bVq,XUq,$Uq;_.TUq=function(a,b){var c=new _.IUq;const d=_.kSq(a);c=new _.qUq(c,b);return _.OSq?new _.DUq(c,b,_.CSq(a,b,d)):new _.AUq(d?new _.JUq(d):new _.KUq,c,b,_.CSq(a,b,d))};UUq=function(a){switch(a){case "permission_denied":return 1;case "feature_not_enabled":return 1E3;case "incognito_location_unavailable":return 1001;case "location_timeout":case 2:case 11:return 3;default:return 2}};
WUq=function(a){if(!a)return Promise.reject(VUq);var b=_.yd(a.Ca());const c=a.Aa(),d=a.Ba(),e=_.mi(a,4);if(!(b&&c&&d&&e))return Promise.reject(new _.p_(2,"Silk API returned a Geolocation position with missing fields."));if(typeof b!=="number")return Promise.reject(new _.p_(2,"Silk API returned a Geolocation position with a timestamp that is not a number."));let f,g,h,k;b={timestamp:b,coords:{latitude:c,longitude:d,accuracy:e,altitude:(f=_.mi(a,5))!=null?f:null,altitudeAccuracy:(g=_.mi(a,6))!=null?
g:null,heading:(h=_.mi(a,7))!=null?h:null,speed:(k=_.mi(a,8))!=null?k:null}};a=_.$g(a,10);return Promise.resolve({JKb:b,pyd:a})};_.aVq=function(){return new XUq(new YUq,new XUq(new ZUq,new $Uq))};VUq=new _.p_(2,"Silk API returned null or undefined.");ZUq=class{getCurrentLocation(a){return _.y(function*(){const b=yield a.getCurrentLocation();if(!b)throw VUq;return{JKb:b}})}dpd(a){return a.isAvailable()}};
YUq=class{getCurrentLocation(a,b,c){return a.Rha(b,c).then(WUq)}dpd(a){return a.isAvailable()&&a.A$()}};bVq=function(a,b,c,d,e){return _.y(function*(){try{return yield a.Aa.getCurrentLocation(b,c,e)}catch(f){const g=f instanceof _.ge?new _.p_(UUq(f.jXb),f.message):new _.p_(2,`Silk API returned an unknown error: ${f}`);return g.code===1E3?a.oa.getCurrentPosition(c,d):Promise.reject(g)}})};
XUq=class{constructor(a,b){this.Aa=a;this.oa=b}getCurrentPosition(a,b,c){const d=this;return _.y(function*(){if(c){var e=new _.SRq;e=_.Og(e,2,c.Lyb);e=_.Og(e,4,c.timeoutMillis);e=_.Yg(e,3,!!c.enableHighAccuracy)}else e=void 0;var f=_.Tb().oa;return(f=yield _.Ze(_.c1a,f))&&d.Aa.dpd(f)?bVq(d,f,a,b,e):d.oa.getCurrentPosition(a,b)})}};$Uq=class{getCurrentPosition(){return Promise.reject(new _.p_(1E3,"Silk API not available."))}};
}catch(e){_._DumpException(e)}
try{
_.t("KHourd");
var pWq=function(a,b){var c=_.Ki(a,72);if(_.z(a,44)||!c)c=void 0;else{var d=new _.Y4a(1655);c=new lWq(d,c)}c=new _.nUq(b.jhc,c);d=_.Oi(a,62);var e=(new mWq).create();if(e){var f=_.kSq(d);e=new _.qUq(e,c);d=_.OSq?new _.DUq(e,c,_.CSq(d,c,f)):new _.AUq(f?new _.JUq(f):new _.KUq,e,c,_.CSq(d,c,f))}else d=null;if(!d)return null;f=(new nWq).from(a,b.ei,d);if(!f)return null;e=(new oWq).from(a);if(!e)return null;b=_.VVq(a,b.ei);return _.RVq(a,c,f,d,e,b)},qWq=function(a,b){return _.y(function*(){let c;return((c=
pWq(a,b))==null?void 0:c.start())||new _.YVq(null)})},rWq=function(a){_.pe(document,"visibilitychange",()=>{document.visibilityState==="visible"&&a()})},sWq={PROMPT:0,vrf:1,yrf:2,xrf:3,urf:5,zrf:6,wrf:7,Arf:8,trf:9,yvf:100,srf:101,0:"PROMPT",1:"NO_PROMPT_BACKOFF",2:"NO_PROMPT_NO_STORAGE",3:"NO_PROMPT_NOT_GRANTED",5:"NO_PROMPT_ALREADY_OPEN",6:"NO_PROMPT_SAME_EVENT",7:"NO_PROMPT_NOT_DIRECT_NAVIGATION",8:"NO_PROMPT_THROTTLED",9:"NO_PRE_PROMPT_GRANTED",100:"PRE_PROMPT",101:"NO_PRE_PROMPT_DENIED"},mWq=
class{create(){for(const a of _.be(_.rUq)){const b=a.create();if(b)return b}return null}},tWq=class{constructor(a){this.oa=a;_.So(a,"/client_streamz/location/location_prompt/prompt_decisions_count",_.Sb("decision"),_.Sb("browser"))}Lj(a,b){_.To(this.oa,"/client_streamz/location/location_prompt/prompt_decisions_count",a,b)}},uWq=class{constructor(a){this.oa=a;_.So(a,"/client_streamz/location/location_prompt/prompt_responses_count",_.Sb("response"),_.Sb("browser"))}Lj(a,b){_.To(this.oa,"/client_streamz/location/location_prompt/prompt_responses_count",
a,b)}};var oWq;_.vWq=new _.io;oWq=class{from(a){for(const b of _.be(_.vWq)){const c=b.from(a);if(c)return c}return null}};var lWq=class{constructor(a,b){this.oa=new _.AOa(a);this.Ba=new tWq(this.oa);this.Ca=new uWq(this.oa);this.Aa=b||"UNKNOWN_BROWSER"}ume(a){this.Ba.Lj(sWq[a],this.Aa)}vme(a){this.Ca.Lj(a?"ACCEPTED":"DENIED",this.Aa)}flush(){this.oa.oa()}};var nWq;_.wWq=new _.io;nWq=class{from(a,b,c){if(_.Oi(a,11)===2)return new _.dWq;for(const d of _.be(_.wWq)){const e=d.from(a,b,c);if(e)return e}return null}};var xWq=function(a,b,c){_.y(function*(){const d=a.getRoot().el();yield qWq(b,{ei:c,jhc:d})})};_.gs(_.gWq,class extends _.ug{static Sa(){return{jsdata:{Nre:_.XVq}}}constructor(a){super(a.Oa);const b=a.jsdata.Nre,c=google.getEI(this.getRoot().el());_.Zg(b,81)?(0,_.Fe)(()=>{xWq(this,b,c)}):xWq(this,b,c);_.z(b,61)&&rWq(function(){qWq(b,{ei:c})})}});
var yWq=function(a){return new Promise((b,c)=>{navigator.geolocation.getCurrentPosition(b,c,a)})},zWq=_.Ma(function(a){return(0,_.xza)(a)&&(0,_.Vba)(a.code)&&(0,_.Uba)(a.message)?!0:!1}),AWq=class{getCurrentPosition(a,b,c){return _.y(function*(){var d=c?{timeout:c.timeoutMillis,maximumAge:c.Lyb,enableHighAccuracy:!!c.enableHighAccuracy}:{timeout:b,maximumAge:15E3};try{const e=yield yWq(d);if(!e)throw new _.p_(2,"The HTML5 geolocation API returned null or undefined.");return{JKb:e}}catch(e){throw d=
e,d instanceof _.p_?d:zWq(d)?new _.p_(d.code,d.message):new _.p_(2,`The HTML5 geolocation API returned an unknown error: ${d}`);}})}};var BWq=class{from(){let a,b;return((a=navigator)==null?0:(b=a.geolocation)==null?0:b.getCurrentPosition)?new AWq:null}};_.RSq&&_.go(_.vWq,BWq);var CWq=class{from(){return _.aVq()}};_.SSq&&_.go(_.vWq,CWq);
_.go(_.wWq,class{from(a,b){if(_.Oi(a,11)!==4)return null;const c=_.kSq(_.Oi(a,62));if(!c)return null;a=_.n(a,_.WVq,47);return new _.kWq(c,b,new _.jWq(c,a))}});

var DWq=class{constructor(a){this.Tna=a}g0a(){const a=this;return _.y(function*(){return _.n_(yield a.Tna.Rba())===2?[0,1]:[3]})}KDb(){}};_.go(_.wWq,class{from(a,b,c){return _.Oi(a,11)===3&&c?new DWq(c):null}});
_.u();
}catch(e){_._DumpException(e)}
try{
_.Iis=_.w("T5VV",[]);
}catch(e){_._DumpException(e)}
try{
_.t("T5VV");
var Jis=function(a){switch(a){case 0:return"BLUR";case 4:return"OFF";case 1:case 2:case 3:return"FILTER";default:return"UNKNOWN"}};_.gs(_.Iis,class extends _.ug{static Sa(){return{}}constructor(a){super(a.Oa);this.oa=_.gd(this.getData("ssc"),-1);this.Aa=_.dh(this.getData("ssl"),!1);this.Ba=_.Ml(this.getData("ssor"),"");typeof window.google!=="undefined"&&(window.google.sss=Jis(this.oa),window.google.sso=this.Aa,window.google.ssor=this.Ba)}});
_.u();
}catch(e){_._DumpException(e)}
try{
_.A2p=_.w("aDVF7",[]);
}catch(e){_._DumpException(e)}
try{
_.t("aDVF7");
_.gs(_.A2p,class extends _.ug{static Sa(){return{}}constructor(a){super(a.Oa);this.oa=_.Ml(this.getData("len"),"");typeof window.google!=="undefined"&&(a=this.oa.slice(-1),window.google.len=a===","?this.oa.slice(0,-1):this.oa)}});
_.u();
}catch(e){_._DumpException(e)}
try{
_.PCB=_.w("rhYw1b",[]);
}catch(e){_._DumpException(e)}
try{
_.t("rhYw1b");
_.gs(_.PCB,class extends _.ug{static Sa(){return{}}constructor(a){super(a.Oa);this.oa=_.Ml(this.getData("dmd"),"");this.deviceType=_.Ml(this.getData("dvt"),"");a=_.N_(1);const b=_.N_(0);a=Math.max(a,b);this.Ba=a<=800?"xs":a<=1E3?"s":a<=1300?"m":a<=2E3?"l":"xl";this.Aa=_.dh(this.getData("iscsc"),!1);typeof window.google!=="undefined"&&(window.google.dvs=this.Ba,window.google.dmd=this.oa,window.google.dvt=this.deviceType,this.Aa&&(window.google.iscsc="1"))}});
_.u();
}catch(e){_._DumpException(e)}
try{
_.Mhs=_.w("FzTajd",[_.zr]);
}catch(e){_._DumpException(e)}
try{
_.t("FzTajd");
var Nhs;Nhs=function(a){if(a.size()<2)a.remove();else{let b;(b=a.first())==null||b.remove();let c;(c=a.last())==null||c.remove()}};
_.Ohs=class extends _.ug{static Sa(){return{service:{Kf:_.xw}}}constructor(a){super(a.Oa);this.Kf=a.service.Kf;this.Aa();(0,_.Fe)(()=>{this.Ba()})}Aa(){const a=document.getElementById(this.getRoot().Rc("aria-owns")||"");a&&(this.oa=new _.Jo(a))}Ba(){this.oa!==void 0&&!this.oa.isEmpty()&&this.oa&&!this.oa.closest(".TQc1id").isEmpty()&&_.QRb(this.Kf,this.oa,this.getRoot())}Ca(){if(this.oa!==void 0&&!this.oa.isEmpty()&&(!this.oa||this.oa.closest(".TQc1id").isEmpty())){var a;(a=this.getRoot().next(".focusSentinel").first())==
null||a.remove();var b;(b=this.getRoot().next(".focusSentinel").first())==null||b.remove();Nhs(this.oa.children().filter(".focusSentinel"));Nhs(this.oa.children().filter(".focusSentinel"))}}};_.Ohs.prototype.$wa$jEKfHe=function(){return this.Ca};_.Ohs.prototype.$wa$NYVLBc=function(){return this.Ba};_.Ohs.prototype.$wa$F0OlHe=function(){return this.Aa};_.gs(_.Mhs,_.Ohs);
_.u();
}catch(e){_._DumpException(e)}
try{
_.t("IhkWbc");

_.u();
}catch(e){_._DumpException(e)}
try{
_.Ths=_.w("oPmHrb",[]);
}catch(e){_._DumpException(e)}
try{
_.Chs=_.qif?800:940;
}catch(e){_._DumpException(e)}
try{
_.t("oPmHrb");
var Uhs=function(a){const b=["script","style","h2"];return a.filter(c=>{const d=c.tagName.toLowerCase();return!b.some(e=>e===d)&&c.hasChildNodes()})},Vhs=function(a){return a.getAttribute("data-rrhs")==="1"};var Whs=function(a){a.Ea=document.getElementById("H3wGC")||void 0;var b=_.ve("center_col");b&&(a.Aa=b,a.Ba=a.Aa.getElementsByClassName("A6K0A"),b=_.ve("rhs"))&&(a.oa=b,a.Na=a.oa.getElementsByClassName("A6K0A"),a.Da=Array.from(a.Ba).concat(Array.from(a.Na)).filter(Vhs).sort((c,d)=>Number(c.getAttribute("data-rpos"))-Number(d.getAttribute("data-rpos"))))},Yhs=function(a){if(a.oa){var b=Array.from(a.oa.children),c=_.ve("jOAHU");c&&(b=b.filter(g=>g!==c).concat(Array.from(c.children)));var d=Uhs(b),e=
d.some(g=>!Vhs(g)&&!g.classList.contains("SjLxGf"));a.oa.classList.toggle("jBpNZc",!e);var f;(f=document.getElementById("main"))==null||f.classList.toggle("n48JGd",!e);d.some(g=>!Vhs(g)||document.evaluate(`//div[@aria-owns="${g.id}"]`,document,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue===null)||Xhs(a,b)}},Zhs=function(a){let b=0,c;const d=(c=a.Da)==null?void 0:c.map(e=>{var f=e.getAttribute("data-rpos");if(f&&a.Ba){var g=Number(f);for(f=!1;b<a.Ba.length;b++){const h=a.Ba[b],k=
h.getAttribute("data-rpos");if(k&&g<=Number(k)){h.insertAdjacentElement("beforebegin",e);f=!0;break}}g=a.Ba[a.Ba.length-1];!f&&g&&g.insertAdjacentElement("afterend",e)}return e});a.Aa&&d&&d.length>0&&(_.Xf(a.Aa,"C6Hrtf"),_.Xf(a.Aa,"O0JaK"));_.a0(_.b0.Job);window.dispatchEvent(new Event("resize"))},$hs=function(a){let b;const c=(b=a.Da)==null?void 0:b.map(d=>{let e;(e=a.Ea)==null||e.insertAdjacentElement("beforebegin",d);return d});c&&c.length>0&&(a.Aa&&_.Xf(a.Aa,"Zea3Wc"),a.oa&&_.Xf(a.oa,"mWTG5b"));
_.a0(_.b0.Job);window.dispatchEvent(new Event("resize"))},ais=function(a,b){a.Aa&&a.oa&&a.Ea&&(b?a.Ja():a.Ka())},Xhs=function(a,b){let c;(c=a.oa)==null||c.removeAttribute("role");b.filter(d=>d.tagName.toLowerCase()==="h2").forEach(d=>{d.remove()})},bis=class extends _.ug{constructor(a){super(a.Oa);Whs(this);this.Ma=_.Chs;Yhs(this);this.Ja=_.us(this).Dc(()=>{Zhs(this)}).build();this.Ka=_.us(this).Dc(()=>{$hs(this)}).build();const b=window.matchMedia(`(max-width: ${this.Ma-.02}px)`);b.addEventListener("change",
c=>{ais(this,c.matches)});this.addOnDisposeCallback(()=>{b.removeEventListener("change",c=>{ais(this,c.matches)})});a=_.dm("cnt");this.Ca=new MutationObserver(()=>{Whs(this)});this.Ca.observe(a,{childList:!0});ais(this,b.matches)}Tb(){this.Ca&&this.Ca.disconnect();super.Tb()}xN(a,b,c){var d=this.getRoot().el().children;!_.pif||d.length<1||(this.sO("GuKejc",_.Xo).then(e=>{for(const f of e)f instanceof _.Ohs&&f.Aa()}),d=d[0],d.setAttribute("aria-owns",c.id),a.insertAdjacentElement(b,d))}};
bis.prototype.$wa$k4Iseb=function(){return this.Tb};_.gs(_.Ths,bis);
_.u();
}catch(e){_._DumpException(e)}
try{
_.Dhs=_.w("LnZNCd",[]);
}catch(e){_._DumpException(e)}
try{
_.t("LnZNCd");
var Ehs=class extends _.m{constructor(a){super(a)}};Ehs.prototype.ob="Sk13Xb";var Fhs=function(a){var b=_.ve("center_col");const c=_.ve("rhs");if(b){if(a.oa!==b||a.Aa!==c)a.Ba=0;a.oa=b;a.Aa=c!=null?c:void 0;a.Ja=!!_.ve("H3wGC");b=(b=_.ve("rhs"))?b.classList.contains("e0KErc"):!1;a.Ea=b}},Ihs=function(a){_.z(a.config,1)||Fhs(a);const b=Ghs();let c=!0;for(const [,d]of b)if(d.matches){Hhs(a);c=!1;break}c&&Hhs(a)},Ghs=function(){return new Map([[12,window.matchMedia(`(max-width: ${_.Chs-.02}px)`)],[14,window.matchMedia("(max-width: 939.98px)")],[16,window.matchMedia("(max-width: 1163.98px)")]])},
Hhs=function(a){Jhs(a);a.Da=(0,_.so)(()=>{if((a.Ja||a.Ea)&&document.visibilityState!=="hidden"&&a.oa&&!(a.Ba>=_.Hd(a.config,2,10))){var b=Khs(),c=_.$f(),d=!0,e=(h,k)=>{c.Gc(h,k);d=!1},f=a.oa.getBoundingClientRect();if(a.Aa){const h=a.Aa.getBoundingClientRect();var g=Math.round(h.left-f.right);const k=Math.round(h.top-f.top);!(h.width*h.height>1)||Math.abs(k)<2&&Math.abs(g-76)<2||e("errsrp-rhs-p",`t:${k},d:${g}/${b}cols`);a.Ja&&b===12?(Math.abs(f.width-652)<2||e("errsrp-main-w",`${Math.round(f.width)}/${b}cols`),
a.Aa.querySelectorAll('[data-rrhs="1"]').length===0&&a.oa.querySelectorAll('[data-rrhs="1"]').length!==0||e("errsrp-rhs-r","no-reflow")):a.Ea&&(g=Math.min(12,Math.max(8,b-6)),Math.abs(f.width-(56*g-20))<2||e("errsrp-main-w",`${Math.round(f.width)}/${b}cols`),Math.abs(h.width-(56*(b-1-g)-20))<2||e("errsrp-rhs-w",`${Math.round(h.width)}/${b}cols`))}else Math.abs(f.width-652)<2||e("errsrp-main-w",`${Math.round(f.width)}/${b}cols`);d||(c.log(),a.Ba++)}},10)},Khs=function(){for(const [a,b]of Ghs()){const c=
a;if(b.matches)return c}return 20},Jhs=function(a){a.Da&&((0,_.to)(a.Da),a.Da=null)},Lhs=class extends _.ug{static Sa(){return{jsdata:{NGe:Ehs}}}constructor(a){super(a.Oa);this.Ea=this.Ja=!1;this.Ba=0;this.config=a.jsdata.NGe;_.z(this.config,1)&&(Fhs(this),a=_.dm("cnt"),this.Ca=new MutationObserver(()=>{Ihs(this)}),this.Ca.observe(a,{childList:!0}));const b=Ghs();for(var [,c]of b)c.addEventListener("change",()=>{Hhs(this)});this.addOnDisposeCallback(()=>{for(const [,d]of b)d.removeEventListener("change",
()=>{Hhs(this)})});Ihs(this);c=_.$f();c.Gc("errsrp-init","init");c.log()}Tb(){this.Ca&&this.Ca.disconnect();super.Tb()}};Lhs.prototype.$wa$k4Iseb=function(){return this.Tb};_.gs(_.Dhs,Lhs);
_.u();
}catch(e){_._DumpException(e)}
try{
_.t("M6QgBb");

_.u();
}catch(e){_._DumpException(e)}
try{
_.Wed=_.w("EO13pd",[_.Er,_.qr,_.HZa,_.IZa,_.xr]);
}catch(e){_._DumpException(e)}
try{
_.Ued=class extends _.m{constructor(a){super(a)}};_.Ved=class extends _.m{constructor(a){super(a)}getInteractionVed(){return _.B(this,4)}};
}catch(e){_._DumpException(e)}
try{
_.t("EO13pd");
var afd,bfd,cfd,dfd,efd,ffd,ifd,jfd,kfd,lfd,mfd,nfd,ofd,pfd,qfd,rfd,sfd,tfd,ufd,vfd,wfd,yfd,zfd,Afd,Cfd,Gfd,Bfd,Dfd,Hfd,Efd,Ffd;afd=class extends _.m{constructor(a){super(a)}};bfd=class extends _.m{constructor(a){super(a)}FW(){return _.B(this,1)}};cfd=class extends _.m{constructor(a){super(a)}};dfd=class extends _.m{constructor(a){super(a)}};efd=class extends _.m{constructor(a){super(a)}Aa(a){return _.bg(this,1,a)}};ffd=[1,2,3,4];_.gfd=function(a,b){return _.Yg(a,1,b)};_.hfd=class extends _.m{constructor(a){super(a)}};
ifd=function(a,b){_.Eb(a,afd,10,b)};jfd=function(a,b){return _.Eb(a,_.zz,14,b)};kfd=function(a,b){return _.Eb(a,_.wz,1,b)};lfd=class extends _.m{constructor(a){super(a)}Ay(){return _.n(this,_.wz,1)}};mfd=function(a){var b=new lfd;return _.Eb(b,_.wz,1,a)};nfd=function(a,b){return _.Yg(a,2,b)};ofd=function(a,b){return _.bg(a,3,b)};pfd=function(a,b){return _.Eb(a,_.sz,4,b)};qfd=function(a,b){_.Eb(a,_.ZD,2,b)};rfd=function(a,b){_.Eb(a,afd,3,b)};
sfd=class extends _.m{constructor(a){super(a)}Xba(){return _.mg(this,_.sD,1,_.ng())}};tfd=function(a,b){return _.Eb(a,_.zz,1,b)};ufd=class extends _.m{constructor(a){super(a)}};vfd=function(a,b){return _.zi(a,14,_.Gdd,b)};wfd=function(a,b){return _.zi(a,16,_.Gdd,b)};_.xfd=function(a,b){return _.zi(a,17,_.Gdd,b)};yfd=function(a){var b=new _.Hdd;return _.zi(b,18,_.Gdd,a)};zfd=_.Rb(_.Ued);Afd=_.Rb(_.Ved);
Cfd=function(a){_.wg(a,{preload:{m4f:_.Ped}});const b=a.Ab("J7OdWb").el();b.ephUSe=()=>{a.odc=!1};_.Qv([new _.mo(b,"insert")],{triggerElement:b});_.yy(b,a.aKa()).then(c=>{a.G$a=!0;a.odc=c}).catch(c=>{a.odc=!1;(_.Gla(c)||_.Hla(c))&&Bfd(a);throw c;})};Gfd=function(a,b){b.subscribe(_.Hdd.prototype.Ca,(c,d)=>Dfd(a,c,d)).subscribe(_.Hdd.prototype.Ba,c=>Efd(c)).subscribe(_.Hdd.prototype.Aa,c=>Ffd(c))};Bfd=function(a){_.un(window,"pageshow",b=>{b.persisted&&!a.G$a&&Cfd(a)})};
Dfd=function(a,b,c){return _.y(function*(){yield new Promise(google.dclc);var d=a.LBd.find(g=>g.amb.Aa().some(h=>_.Ucd(h)===_.B(b,1)));const e=new sfd;let f;((f=a.config)==null?0:_.fi(f,afd,123))&&rfd(e,_.n(a.config,afd,123));if(d)qfd(_.Eb(e,_.zz,4,d.amb),d.Lac),_.zi(c,11,_.Gdd,e);else if(d=(new _.gu(a.history.getCurrentUrl(),{nWa:_.RJa})).oa.get("vssid")||"",d=(yield a.cHd.promise)(d))_.Eb(e,_.zz,4,d),_.zi(c,11,_.Gdd,e)})};
Hfd=function(a,b,c,d,e,f,g,h){var k=new _.Cdd;g=_.Og(k,8,g);g=_.Og(g,16,_.vg);e=e!=null?e:b==null?void 0:_.Ii(b,19);e=_.Ah(g,12,e);b&&_.Eb(e,_.ZD,6,b);c&&_.bg(e,7,c);d!=null&&_.bg(e,17,d);f!=null&&_.Ah(e,18,f);a.config&&_.fi(a.config,afd,123)&&ifd(e,_.n(a.config,afd,123));h&&_.bg(e,13,h);return e};
Efd=function(a){return _.y(function*(){if(_.hi(a,cfd,1,ffd))_.dr();else if(_.hi(a,bfd,2,ffd)){var b=_.Mg(a,bfd,2,ffd);_.yn(window,"attn_dom_immersive",!1,new _.Xed(b.FW(),_.z(b,2)))}else _.hi(a,efd,3,ffd)?(b=_.Mg(a,efd,3,ffd),b=_.B(b,1),_.Qed(b)):_.hi(a,dfd,4,ffd)&&_.Red()})};Ffd=function(a){return _.y(function*(){_.Xf(document.body,"xHsTDe",{bmb:_.B(a,1)})})};
_.Ifd=class extends _.ug{static Sa(){return{service:{history:_.PD,navigation:_.Ez,Jnb:_.ydd,Z8a:_.zdd,window:_.Nu}}}constructor(a){super(a.Oa);this.G$a=!1;this.config=this.W0=null;this.LBd=[];this.odc=!0;this.cHd=new _.wh;this.history=a.service.history;this.kc=a.service.navigation;this.Jnb=a.service.Jnb;var b=this.Z8a=a.service.Z8a;b.oa.push(this);b.Aa!=null&&(b.Aa.resolve(this),b.Aa=null);this.C1();this.document=a.service.window.getDocument()}Tb(){var a=this.Z8a;const b=a.oa.indexOf(this);b>=0&&
a.oa.splice(b,1);super.Tb()}sne(a){a=zfd(a.data);this.initialize(_.n(a,_.Bz,1),_.n(a,_.zz,2),_.n(a,_.ZD,3))}Yac(){if(!this.W0){var a=_.vdd;a.yj.oa.QI()&&_.ap(a.yj,"uvpbs");this.init();_.$ed();this.etd()}}initialize(a,b,c){this.config=a;this.LBd.push({amb:b,Lac:c});this.Yac()}init(){Cfd(this);if(this.W0=_.Ldd())Gfd(this,this.W0),this.W0.initialize(_.tka())}BJe(a){this.cHd.resolve(a)}aKa(){return{iT:!0,QMa:()=>{this.dirty()}}}etd(){this.W0&&this.W0.Aa&&this.W0.Aa.then(()=>{var a=_.vdd;a.yj.oa.QI()&&
(_.ap(a.yj,"uvpbe"),a.yj.log())})}kvb(a,b,c,d,e,f,g,h,k){const l=this;return _.y(function*(){var p;if(_.dLb&&((p=google)==null?0:p.zl)&&google.zl.qvoc)return google.zl.qvoc=!1,Promise.resolve();p=Math.round(h);l.Jnb.Pc(p);const q=a.Aa()[a.Ii()],r=q==null?void 0:_.yi(q,_.xu,1,_.eIc).getViewerType();r!==25&&r!==47&&(_.Oed.oa._guestSettings={fetchPriority:"high"});l.Aqb();if(!l.W0||!l.odc)return Promise.resolve().then(()=>{var x=b==null?void 0:_.kj(b,19),A=l.kc,G=_.fo(new _.Yn(l.history.getCurrentUrl()),
"q")||"";(x=_.Ted(q,G,d,x||null))&&A.navigateTo(x)});if(!q)return _.ee(Error("Mh")),Promise.resolve();p=jfd(Hfd(l,b,d,e,f,g,p,k),a);if(c==null?0:_.fi(c,afd,123))ifd(p,_.n(c,afd,123));else{let x;((x=l.config)==null?0:_.fi(x,afd,123))&&ifd(p,_.n(l.config,afd,123))}yield l.Cjc(p,q,d,b);l.document.dispatchEvent(new CustomEvent("viewerOpenEventHandled"))})}Cjc(a,b,c,d){const e=this;return _.y(function*(){e.Aqb();if(!e.W0){const f=Error("Nh");_.ee(f);return Promise.reject(f)}return e.W0.sendMessage((new _.Hdd).Cjc(a),
!0).catch(f=>{_.ee(Error("Oh`"+f.message));var g=d==null?void 0:_.kj(d,19);f=e.kc;var h=_.fo(new _.Yn(e.history.getCurrentUrl()),"q")||"";(g=_.Ted(b,h,c,g||null))&&f.navigateTo(g)})})}Nhe(a){a=Afd(a.data);this.kvb(_.n(a,_.zz,1),_.n(a,_.ZD,2)||null,null,_.B(a,3)||null,a.getInteractionVed()||null,_.Hd(a,5)||null,null,_.Ni(a,6),_.B(a,7)||null)}Phe(a){const b=this;return _.y(function*(){var c=a.data;const d=c.params.Rn;if(!d)return _.ee(Error("Ph")),Promise.resolve();d==null||_.yi(d,_.xu,1,_.eIc).getViewerType();
let e;const f=pfd(ofd(nfd(mfd(d),c.Aa),(e=c.oa)==null?void 0:e.id),c.params.wc);d.bV();b.Aqb();return b.W0?yield b.W0.sendMessage(yfd(f)).catch(g=>{_.ee(Error("Qh`"+g.message))}):(c=Error("Nh"),_.ee(c),Promise.reject(c))})}jFc(a){const b=this;return _.y(function*(){b.W0&&(yield b.W0.sendMessage(_.xfd(new _.Hdd,_.gfd(new _.hfd,!!a.data))).catch(c=>{_.ee(Error("Rh`"+c.message))}))})}dnb(a){this.Aqb();return this.W0?this.W0.sendMessage(vfd(new _.Hdd,tfd(new ufd,a))).catch(b=>{_.ee(Error("Sh`"+b.message))}):
(a=Error("Nh"),_.ee(a),Promise.reject(a))}nFc(a){this.Aqb();return this.W0?this.W0.sendMessage(wfd(new _.Hdd,kfd(new _.Ddd,a))).catch(b=>{_.ee(Error("Th`"+b.message))}):(a=Error("Nh"),_.ee(a),Promise.reject(a))}Aqb(){this.W0||(_.ee(Error("Uh"),{level:2}),this.Yac())}C1(){}};_.Ifd.prototype.$wa$npAYtf=function(){return this.C1};_.Ifd.prototype.$wa$Nj7Yd=function(){return this.Aqb};_.Ifd.prototype.$wa$A1kDjc=function(){return this.jFc};_.Ifd.prototype.$wa$gj6b3c=function(){return this.Phe};
_.Ifd.prototype.$wa$dwOkab=function(){return this.Nhe};_.Ifd.prototype.$wa$NMQPwb=function(){return this.etd};_.Ifd.prototype.$wa$fjjfVb=function(){return this.Yac};_.Ifd.prototype.$wa$f0xwYb=function(){return this.sne};_.Ifd.prototype.$wa$k4Iseb=function(){return this.Tb};_.gs(_.Wed,_.Ifd);
var Jfd=function(a,b,c){a=new _.co(_.yl(a.url));b=!!a.get("imgrc")&&a.get("imgrc")!=="_";if(a.get("vhid")||b){b=!!a.get("oshop");var d=!!a.get("epd");if(b||d)if(c.userInitiated)a.remove("oshop"),a.remove("oshopproduct"),a.remove("epd"),c=new _.Yn(this.history.getCurrentUrl()),_.bo(c,a.toString()),this.history.oa(c.toString());else try{const e=_.gfd(new _.hfd,!0);this.W0.sendMessage(_.xfd(new _.Hdd,e))}catch(e){this.W0.sendMessage((new _.Hdd).Cjc(new _.Cdd))}}};_.Ifd.prototype.C1=function(){this.history.addListener(Jfd.bind(this))};
_.Ifd.prototype.$wa$npAYtf=function(){return this.C1};

_.u();
}catch(e){_._DumpException(e)}
try{
_.mDB=_.w("NmZKpe",[_.fr]);
}catch(e){_._DumpException(e)}
try{
_.t("NmZKpe");
_.gs(_.mDB,class extends _.ug{static Sa(){return{service:{location:_.sv}}}constructor(a){super(a.Oa);this.Ec=a.service.location;(new _.gu(this.Ec.location.hash)).oa.has("sv")&&_.Ze(_.QZa,this.Xm())}});
_.u();
}catch(e){_._DumpException(e)}
try{
_.iTp=_.w("I9y8sd",[]);
}catch(e){_._DumpException(e)}
try{
_.t("I9y8sd");
var jTp=function(){return google.ht&&google.ht<Date.now()&&!google.fuht?!0:!1},kTp=function(a){a=getComputedStyle(a);if(a.display==="none")return"display: none";if(Number(a.opacity)<.5)return`opacity: ${a.opacity}`;if(a.visibility==="hidden")return"visibility: hidden"},lTp=function(a,b,c,d,{logError:e}){d=_.$d(d);b=`${b}-${c}-${_.Dla(d)}`;const f=a.get(b),g=_.ae(d,"am");if(g){if(f){if(g===f)return;let h=`k=${_.Dla(d)}`;(d=_.ae(d,"ck"))&&(h=`${h}.ck=${d}`);e(Error("Zu`"+JSON.stringify({type:c,l_f:h,
xXf:f,eXf:g})))}a.set(b,g)}},nTp=function(a){if(a.toggle){var b;a.sampleRate=(b=a.sampleRate)!=null?b:.01;mTp.push(a)}},oTp={name:"umods"},pTp=!!(_.Oh[19]&8192),qTp=!!(_.Oh[19]>>14&1),rTp=!!(_.Oh[19]>>15&1),sTp=!!(_.Oh[19]>>16&1),tTp=!!(_.Oh[19]>>17&1),uTp=!!(_.Oh[19]>>18&1),vTp=!!(_.Oh[19]>>19&1);var wTp=["google.com","youtube.com","ampproject.org",(new URL(location.href)).host];var mTp=[],xTp=[],yTp=class extends _.ug{static Sa(){return{}}constructor(a){super(a.Oa);this.Ca=Math.random();this.Aa=!1;this.logError=this.logError.bind(this);window.addEventListener("pagehide",()=>{this.Aa=!0});window.addEventListener("pageshow",()=>{this.Aa=!1});google.sx(null,()=>{(0,_.so)(()=>{this.Ba()},2E3)})}Ba(){if(!this.Aa)for(const a of mTp)this.sample(a,()=>{a.run({logError:(b,c={})=>{this.logError(a.name,b,c)}})})}logError(a,b,c={}){if(!this.oa){this.oa={};for(const d of xTp)this.sample(d,
()=>{const e=d.run();e&&(this.oa=Object.assign({},this.oa,e))})}_.ee(b,{level:0,Df:Object.assign({},{src:"bad_srp_detection"},c,this.oa)});qTp&&navigator.sendBeacon(`/gen_204?atyp=i&bsf=${a}.1&ei=${(0,_.Tl.Hw)()}`,"")}sample(a,b){((a.r_f?Math.random():this.Ca)<(a.sampleRate||0)||pTp)&&b()}};yTp.prototype.$wa$rT3LBf=function(){return this.Ba};
nTp({name:"fi",run:function({logError:a}){const b={},c=Array.from(document.querySelectorAll("iframe")).map(d=>{try{return d.src&&d.src.length!==0?(new URL(d.src)).hostname:void 0}catch(e){return e.toString()}}).filter(d=>{if(!d)return!1;d=d.split(".");for(const e of wTp)if(d.slice(-1*e.split(".").length).join(".").toLowerCase()===e)return!1;return!0});if(c.length){b.count=String(c.length);for(let d=0;d<Math.min(c.length,3);d++)b[`iframe_${d+1}`]=c[d];a(Error("$u"),b)}},toggle:sTp});
nTp({name:"hp",run:function({logError:a}){if(!jTp()){for(var b=document.elementFromPoint(window.innerWidth/2,window.innerHeight/2),c=[];b;)c.unshift(b),b=b.parentElement;for(const d of c){if(d.offsetWidth<window.innerWidth*.6||d.offsetHeight<200)break;const e=kTp(d);if(e){const f=d;(0,_.so)(()=>{e===kTp(f)&&a(Error("av"),{hiddenProperty:e,id:f.id,tagName:f.tagName,classes:f.classList.value,styles:f.getAttribute("style")||""})},1E3);break}}}},toggle:rTp});
nTp({name:"sp",run:function({logError:a}){var b;if(b=!jTp())b=document.body.querySelector("[jsname=KG3hVc]"),b=!(b&&window.getComputedStyle(b).display!=="none");if(b){b=document.body.clientHeight;var c,d=((c=document.getElementById("rcnt")||document.getElementById("center_col"))==null?void 0:c.clientHeight)||0;(b<400||d<100)&&a(Error("bv"),{pageHeight:String(b),resultsHeight:String(d)})}},toggle:rTp});nTp({name:"qm",run:function({logError:a}){document.compatMode==="BackCompat"&&a(Error("cv"))},toggle:tTp});
nTp({name:"um",run:function({logError:a}){var b=google.erd;if(b){var c=b.bv;if(c&&(b=b.dpf)){var d,e=(d=navigator)==null?void 0:d.userAgent;if(e){d=_.sf("s",oTp);c=`${c}-${b}-${e}`;var f;(b=(f=google.xjs)==null?void 0:f.basejs)&&lTp(d,c,"jsurl",b,{logError:a});var g;(f=(g=google.xjs)==null?void 0:g.basecss)&&lTp(d,c,"cssurl",f,{logError:a});var h;(g=(h=google.xjs)==null?void 0:h.basecomb)&&lTp(d,c,"comburl",g,{logError:a})}}}},toggle:vTp});
var zTp={name:"nn",run:function(){var a=document.querySelectorAll("script:not([nonce])");if(a.length!==0){var b={nonce_count:String(a.length)},c=0;for(const d of a){a=d.src;let e;if((e=a)==null?0:e.startsWith("https://www.gstatic.com/"))return;if(c++>3)break;let f;const g=(f=d.textContent)==null?void 0:f.substring(0,300);g&&(b[`nonce_script_${c}`]=g);a&&(b[`nonce_src_${c}`]=a)}return b}},toggle:uTp};if(zTp.toggle){var ATp;zTp.sampleRate=(ATp=zTp.sampleRate)!=null?ATp:1;xTp.push(zTp)}_.gs(_.iTp,yTp);
_.u();
}catch(e){_._DumpException(e)}
try{
_.t("xBbsrc");
_.G4o=new _.Ye(_.q3a);
_.u();
}catch(e){_._DumpException(e)}
try{
_.M4o=_.w("DLOxie",[_.q3a,_.fr]);
}catch(e){_._DumpException(e)}
try{
var oid,pid,qid,rid,tid,uid,wid,vid,yid,zid,Aid,xid;oid=function(...a){return new _.ANa(a.map(_.woa))};pid=_.ca.URL;_.sid=(_.ca==null?void 0:(qid=_.ca.document)==null?void 0:qid.baseURI)||((rid=_.ca.location)==null?void 0:rid.href)||"";try{new pid("http://example.com"),tid=!0}catch(a){tid=!1}uid=tid;
wid=class{constructor(a){this.oa=new Map;a.indexOf("?")==0&&(a=a.substring(1));a=a.split("&");for(let c of a){a=c;let d="";var b=c.split("=");b.length>1&&(a=decodeURIComponent(b[0].replace("+"," ")),d=decodeURIComponent(b[1].replace("+"," ")));b=this.oa.get(a);b==null&&(b=[],this.oa.set(a,b));b.push(d)}}get(a){return(a=this.oa.get(a))&&a.length?a[0]:null}getAll(a){return[...(this.oa.get(a)||[])]}has(a){return this.oa.has(a)}[Symbol.iterator](){return oid(..._.zNa(this.oa,a=>{const b=a[0];return _.zNa(a[1],
c=>[b,c])}))}toString(){return vid(this)}};vid=function(a){const b=c=>encodeURIComponent(c).replace(/[!()~']|(%20)/g,d=>({"!":"%21","(":"%28",")":"%29","%20":"+","'":"%27","~":"%7E"})[d]);return Array.from(a,c=>b(c[0])+"="+b(c[1])).join("&")};
yid=function(a){const b=_.qm("A");let c;try{_.Hc(b,_.ac(a)),c=b.protocol}catch(e){throw Error("gi`"+a);}if(c===""||c===":"||c[c.length-1]!=":")throw Error("gi`"+a);if(!xid.has(c))throw Error("gi`"+a);if(!b.hostname)throw Error("gi`"+a);const d=b.href;a={href:d,protocol:b.protocol,username:"",password:"",hostname:b.hostname,pathname:"/"+b.pathname,search:b.search,hash:b.hash,toString:()=>d};xid.get(b.protocol)===b.port?(a.host=a.hostname,a.port="",a.origin=a.protocol+"//"+a.hostname):(a.host=b.host,
a.port=b.port,a.origin=a.protocol+"//"+a.hostname+":"+a.port);return a};zid=function(a,b){return a&&b?a+":"+b+"@":a?a+"@":b?":"+b+"@":""};
Aid=function(a){let b;try{b=new pid(a)}catch(d){throw Error("gi`"+a);}const c=xid.get(b.protocol);if(!c)throw Error("gi`"+a);if(!b.hostname)throw Error("gi`"+a);if(b.origin!="null")return b;a={href:b.href,protocol:b.protocol,username:"",password:"",host:b.host,port:b.port,hostname:b.hostname,pathname:b.pathname,search:b.search,hash:b.hash};a.origin=c===b.port?b.protocol+"//"+b.hostname:b.protocol+"//"+b.hostname+":"+b.port;return a};
_.dE=function(a,b){if(uid){if(!b)return Aid(a);b=Aid(b);try{return Aid(a)}catch(e){}return new pid(a,b.href)}if(!b)return yid(a);b=yid(b);try{return yid(a)}catch(e){}const c=b.protocol+"//"+zid(b.username,b.password)+b.host;var d=a[0];d==="/"||d==="\\"?a=c+a:d==="?"?a=c+b.pathname+a:d&&d!=="#"?(d=b.pathname.lastIndexOf("/"),a=c+(d>0?b.pathname.substring(0,d):"")+"/"+a):a=c+b.pathname+b.search+a;return yid(a)};xid=new Map([["http:","80"],["https:","443"],["ws:","80"],["wss:","443"],["ftp:","21"]]);
_.eE=function(a){return uid&&a.searchParams?a.searchParams:new wid(a.search)};
_.Bid=function(a,b){let c={};b&&(c.protocol=b.protocol,c.username=b.username,c.password=b.password,c.hostname=b.hostname,c.port=b.port,c.pathname=b.pathname,c.search=b.search,c.hash=b.hash);Object.assign(c,a);if(c.port&&c.port[0]===":")throw Error("hi");c.hash&&c.hash[0]!="#"&&(c.hash="#"+c.hash);a.search?a.search[0]!="?"&&(c.search="?"+a.search):a.searchParams&&(c.search="?"+vid(a.searchParams),c.searchParams=void 0);a="";c.protocol&&(a+=c.protocol+"//");a+=zid(c.username,c.password);a+=c.hostname||
"";c.port&&(a+=":"+c.port);a+=c.pathname||"";a+=c.search||"";a+=c.hash||"";return _.dE(a)};
}catch(e){_._DumpException(e)}
try{
_.t("DLOxie");
var N4o=function(a){try{const b=_.dE(a);return b.hostname!=null&&b.hostname.endsWith(".search.translate.goog")}catch(b){return!1}},O4o=RegExp("^(.+)[.]([a-zA-Z]+)2([a-zA-Z]+)[.]search[.]translate[.]goog");var P4o={childList:!0,subtree:!0,attributes:!0,attributeFilter:["href"]},T4o=function(a,b){if(N4o(b.href))try{var c=b.href;if(!N4o(c))throw Error("Jt`"+c);const e=_.dE(c),f=e.hostname.match(O4o);if(!f||f.length!==4)throw Error("Kt`"+c);const g=f[1],h=f[2],k=f[3];if(h.length!==2||!/^[a-zA-Z]+$/.test(h))throw Error("Lt`"+c);if(k.length!==2||!/^[a-zA-Z]+$/.test(k))throw Error("Mt`"+c);var d={Ega:_.Bid({hostname:g},e).href,Xta:h,Hoa:k};_.$f().Gc("toledo_url",b.href).log();_.Hc(b,d.Ega)}catch(e){}(a.Aa||
a.Ca)&&(d=Q4o(a,b))&&(R4o(a,b,d)||S4o(b,d))},Q4o=function(a,b){if(!b.href)return null;let c,d;try{b=c=_.dE(b.href);let f=!1;if((b.hostname==="google.com"||b.hostname==="www.google.com"||b.hostname===a.Ec.location.hostname)&&b.pathname==="/url"){f=!0;var e=_.eE(b);e.has("q")?b=_.dE(e.get("q")):e.has("url")&&(b=_.dE(e.get("url")))}({url:c,kxb:d}={url:b,kxb:f})}catch(f){return null}if(c.hostname!=="translate.google.com"||c.pathname!=="/translate")return null;a=_.eE(c);if(!a.has("u")||!a.has("tl")||!a.has("sl"))return null;
e=a.get("u");e+=c.hash!=="#"?c.hash:"";return{kxb:d,iZb:c.href,u8a:e,sYb:a.get("tl"),WXa:a.get("sl")}},R4o=function(a,b,c){if(!a.oa.isAvailable())return!1;_.Hc(b,c.u8a);b.addEventListener("click",d=>{d.preventDefault();_.Rv(b,{userAction:3,data:{url:c.iZb}});a.oa.oa(c.u8a,c.sYb,c.WXa,_.ed())});return!0},S4o=function(a,b){HTMLAnchorElement.prototype.hasOwnProperty("hrefTranslate")&&(_.Hc(a,b.u8a),a.setAttribute("hrefTranslate",b.sYb),b.kxb&&a.addEventListener("click",()=>_.y(function*(){yield _.Rv(a,
{userAction:3,data:{url:b.iZb}})})))},U4o=class extends _.ug{static Sa(){return{service:{qk:_.G4o,Ec:_.sv}}}constructor(a){super(a.Oa);this.Ei=null;this.Ba=b=>{for(const c of b)c.type==="childList"?c.addedNodes.forEach(d=>{d.nodeType===Node.ELEMENT_NODE&&(d.matches("a")&&T4o(this,d),d instanceof Element&&d.querySelectorAll("a").forEach(e=>{T4o(this,e)}))}):c.type==="attributes"&&c.attributeName==="href"&&c.target.matches("a")&&T4o(this,c.target)};this.oa=a.service.qk;this.Ec=a.service.Ec;this.Ei=
new MutationObserver(this.Ba);this.Aa=this.getData("cte").Lb();this.Ca=this.getData("ste").Lb()}qe(){document.documentElement.querySelectorAll("a").forEach(a=>{T4o(this,a)});this.Ei.observe(document.body,P4o)}ud(){super.ud();this.Ei&&this.Ei.disconnect()}};U4o.prototype.$wa$mU5qzf=function(){return this.ud};U4o.prototype.$wa$npT2md=function(){return this.qe};_.gs(_.M4o,U4o);
_.u();
}catch(e){_._DumpException(e)}
})(this._s);
// Google Inc.
