paths:
  image_georef: "../interim/georef.tif"
  out_geojson: "../processed/boundary.geojson"

extract:
  hsv_lower: [90, 50, 50]
  hsv_upper: [130, 255, 255]
  close_kernel: 9
  simplify_ratio: 0.0005
  min_ring_length: 20

post:
  smooth_radius_m: 70 # bigger = more rounded corners
  simplify_tolerance_m: 10 # small cleanup after smoothing
  include_holes: false # drop all interior holes for now
  min_hole_area_sqkm: 0.25 # only used if include_holes: true
  max_perimeters: 1 # keep top 1 or 2 outer polygons
  shave_radius_m: 40 # trims outward spikes (peaks); set 0 to disable
  buffer_round_m: 30 # out-in buffer to soften large outer corners
