service_name: Zoox Las Vegas
provider: Zoox
city: Las Vegas
start_date: September 2025
booking:
  channel: 
  url: 
safety: driverless  # driverless | safety_driver | attendant
ridership:
  period: 
  trips: 
  source_url: 
notes: 
links:
  - title: 
    url:
