service_name: Waymo Los Angeles
provider: Waymo
city: Los Angeles
start_date: June 2025
booking:
  channel: 
  url: 
safety: driverless  # driverless | safety_driver | attendant
ridership:
  period: 
  trips: 
  source_url: 
notes: 
links:
  - title: 
    url:
